// src/client/components/EditorSettings.tsx
import type { TandemSettings } from "../hooks/useTandemSettings";
import { sectionLabelStyle } from "./settingsStyles";

interface EditorSettingsProps {
  settings: TandemSettings;
  onUpdate: (partial: Partial<TandemSettings>) => void;
}

export function EditorSettings({ settings, onUpdate }: EditorSettingsProps) {
  return (
    <div>
      <div style={sectionLabelStyle}>
        Editor Width:{" "}
        <span style={{ fontWeight: 400, textTransform: "none" }}>
          {settings.editorWidthPercent}%
        </span>
      </div>
      <div style={{ fontSize: "10px", color: "var(--tandem-fg-subtle)", marginBottom: "6px" }}>
        How much of the available space the editor text fills
      </div>
      <input
        data-testid="editor-width-slider"
        type="range"
        min={50}
        max={100}
        step={5}
        value={settings.editorWidthPercent}
        onChange={(e) => onUpdate({ editorWidthPercent: Number(e.target.value) })}
        style={{ width: "100%", accentColor: "var(--tandem-accent)" }}
        aria-label="Editor width"
      />
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          fontSize: "10px",
          color: "var(--tandem-fg-subtle)",
        }}
      >
        <span>50%</span>
        <span>100%</span>
      </div>
    </div>
  );
}

// src/client/components/EditorSettings.svelte
<script lang="ts">
  import type { TandemSettings } from "../hooks/useTandemSettings.svelte";

  interface Props {
    settings: TandemSettings;
    onUpdate: (partial: Partial<TandemSettings>) => void;
  }

  let { settings, onUpdate }: Props = $props();

  const sectionLabelStyle =
    "font-size: 11px; font-weight: 600; color: var(--tandem-fg); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;";
</script>

<div>
  <div style={sectionLabelStyle}>
    Editor Width:
    <span style="font-weight: 400; text-transform: none;">
      {settings.editorWidthPercent}%
    </span>
  </div>
  <div style="font-size: 10px; color: var(--tandem-fg-subtle); margin-bottom: 6px;">
    How much of the available space the editor text fills
  </div>
  <input
    data-testid="editor-width-slider"
    type="range"
    min={40}
    max={100}
    step={5}
    value={settings.editorWidthPercent}
    oninput={(e) => onUpdate({ editorWidthPercent: Number((e.target as HTMLInputElement).value) })}
    style="width: 100%; accent-color: var(--tandem-accent);"
    aria-label="Editor width"
  />
  <div style="display: flex; justify-content: space-between; font-size: 10px; color: var(--tandem-fg-subtle);">
    <span>40%</span>
    <span>100%</span>
  </div>
</div>
