// src/client/components/FileOpenDialog.svelte
<script lang="ts">
import { API_BASE, readFileForUpload } from "../utils/fileUpload.js";
import {
  addRecentFile,
  clearRecentFiles,
  loadRecentFiles,
  saveRecentFiles,
} from "../utils/recentFiles.js";

interface Props {
  onClose: () => void;
}

const { onClose }: Props = $props();

type Mode = "path" | "upload";

// #478: Default to "upload" (OS file picker) instead of "path"
let mode = $state<Mode>("upload");
let filePath = $state("");
let error = $state<string | null>(null);
let loading = $state(false);
let dragOver = $state(false);
let fileInputEl: HTMLInputElement | undefined = $state();
let recentFiles = $state<string[]>(loadRecentFiles());

function pushRecent(path: string) {
  recentFiles = (() => {
    const updated = addRecentFile(recentFiles, path);
    saveRecentFiles(updated);
    return updated;
  })();
}

function handleClearRecent() {
  clearRecentFiles();
  recentFiles = [];
}

async function openByPath(pathToOpen: string) {
  if (loading) return;
  error = null;
  loading = true;
  try {
    const res = await fetch(`${API_BASE}/open`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ filePath: pathToOpen }),
    });
    const data = await res.json();
    if (!res.ok) {
      error = data.message ?? "Failed to open file";
      return;
    }
    pushRecent(pathToOpen);
    onClose();
  } catch (err) {
    console.error("FileOpenDialog: path open failed", err);
    if (err instanceof SyntaxError) {
      error = "Server returned an unexpected response";
    } else if (err instanceof TypeError) {
      error = "Unexpected response format";
    } else {
      error = "Cannot reach server. Is it running?";
    }
  } finally {
    loading = false;
  }
}

function handlePathSubmit() {
  if (!filePath.trim()) return;
  openByPath(filePath.trim());
}

async function uploadFile(file: File) {
  if (loading) return;
  error = null;
  loading = true;
  try {
    const content = await readFileForUpload(file);
    const res = await fetch(`${API_BASE}/upload`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ fileName: file.name, content }),
    });
    const data = await res.json();
    if (!res.ok) {
      error = data.message ?? "Failed to open file";
      return;
    }
    onClose();
  } catch (err) {
    console.error("FileOpenDialog: upload failed", err);
    if (err instanceof SyntaxError) {
      error = "Server returned an unexpected response";
    } else if (err instanceof TypeError) {
      error = "Unexpected response format";
    } else {
      error = "Cannot reach server. Is it running?";
    }
  } finally {
    loading = false;
  }
}

function handleFileDrop(e: DragEvent) {
  e.preventDefault();
  dragOver = false;
  const file = e.dataTransfer?.files[0];
  if (file) uploadFile(file);
}

function handleFileSelect(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  if (file) uploadFile(file);
}
</script>

<div
  role="dialog"
  aria-modal="true"
  aria-label="Open File"
  tabindex={-1}
  style="position: fixed; inset: 0; z-index: 1000; display: flex; align-items: flex-start; justify-content: center; padding-top: 80px; background: rgba(0,0,0,0.3);"
  onclick={(e) => {
    if (e.target === e.currentTarget) onClose();
  }}
  onkeydown={(e) => {
    if (e.key === "Escape") onClose();
  }}
>
  <div
    style="background: var(--tandem-surface); border-radius: 8px; box-shadow: 0 8px 30px rgba(0,0,0,0.15); width: 440px; padding: 20px;"
    data-testid="file-open-dialog"
  >
    <div style="display: flex; justify-content: space-between; margin-bottom: 16px;">
      <h3 style="margin: 0; font-size: 15px; font-weight: 600; color: var(--tandem-fg);">
        Open File
      </h3>
      <button
        onclick={onClose}
        style="background: none; border: none; cursor: pointer; font-size: 16px; color: var(--tandem-fg-subtle);"
      >
        ×
      </button>
    </div>

    <!-- Mode toggle — #478: "Upload" renamed to "Open" -->
    <div style="display: flex; gap: 8px; margin-bottom: 16px;">
      <button
        onclick={() => (mode = "path")}
        style={`flex: 1; padding: 6px; font-size: 13px; border: 1px solid var(--tandem-border); border-radius: 4px; cursor: pointer; background: ${mode === "path" ? "var(--tandem-accent)" : "var(--tandem-surface)"}; color: ${mode === "path" ? "var(--tandem-accent-fg)" : "var(--tandem-fg)"};`}
      >
        File Path
      </button>
      <button
        onclick={() => (mode = "upload")}
        style={`flex: 1; padding: 6px; font-size: 13px; border: 1px solid var(--tandem-border); border-radius: 4px; cursor: pointer; background: ${mode === "upload" ? "var(--tandem-accent)" : "var(--tandem-surface)"}; color: ${mode === "upload" ? "var(--tandem-accent-fg)" : "var(--tandem-fg)"};`}
      >
        Open
      </button>
    </div>

    {#if mode === "path"}
      <div>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          autofocus
          type="text"
          placeholder="Paste absolute file path..."
          bind:value={filePath}
          onkeydown={(e) => {
            if (e.key === "Enter") handlePathSubmit();
          }}
          style="width: 100%; padding: 8px 10px; font-size: 13px; border: 1px solid var(--tandem-border-strong); border-radius: 4px; box-sizing: border-box; background: var(--tandem-surface); color: var(--tandem-fg);"
          data-testid="file-path-input"
        />
        <button
          onclick={handlePathSubmit}
          disabled={loading || !filePath.trim()}
          style={`margin-top: 10px; width: 100%; padding: 8px; font-size: 13px; font-weight: 500; border: none; border-radius: 4px; cursor: ${loading ? "wait" : "pointer"}; background: ${loading ? "var(--tandem-fg-subtle)" : "var(--tandem-accent)"}; color: var(--tandem-accent-fg); opacity: ${!filePath.trim() ? 0.5 : 1};`}
          data-testid="file-open-submit"
        >
          {loading ? "Opening..." : "Open"}
        </button>

        <!-- Recent files -->
        {#if recentFiles.length > 0}
          <div data-testid="recent-files-list" style="margin-top: 14px;">
            <div
              style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;"
            >
              <span
                style="font-size: 11px; color: var(--tandem-fg-subtle); text-transform: uppercase; letter-spacing: 0.05em;"
              >
                Recent
              </span>
              <button
                data-testid="clear-recent-files"
                onclick={handleClearRecent}
                type="button"
                style="background: none; border: none; color: var(--tandem-fg-subtle); font-size: 11px; cursor: pointer; padding: 0; text-decoration: underline;"
              >
                Clear all
              </button>
            </div>
            <div
              style="max-height: 150px; overflow-y: auto; display: flex; flex-direction: column; gap: 2px;"
            >
              {#each recentFiles as p, i (p)}
                {@const parts = p.split(/[/\\]/)}
                {@const filename = parts.at(-1) ?? p}
                {@const dir = parts.slice(0, -1).join("/") || "/"}
                <button
                  type="button"
                  data-testid={`recent-file-${i}`}
                  onclick={() => {
                    filePath = p;
                    openByPath(p);
                  }}
                  style="background: none; border: none; padding: 6px 8px; border-radius: 4px; cursor: pointer; text-align: left; display: flex; flex-direction: column; gap: 1px;"
                  onmouseenter={(e) => {
                    (e.currentTarget as HTMLButtonElement).style.background =
                      "var(--tandem-surface-muted)";
                  }}
                  onmouseleave={(e) => {
                    (e.currentTarget as HTMLButtonElement).style.background = "transparent";
                  }}
                >
                  <span style="font-size: 13px; color: var(--tandem-fg);">{filename}</span>
                  <span
                    style="font-size: 11px; color: var(--tandem-fg-subtle); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 380px;"
                  >
                    {dir}
                  </span>
                </button>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    {:else}
      <!-- #478: "Uploading..." renamed to "Opening..." -->
      <div
        role="button"
        tabindex={0}
        ondragover={(e) => {
          e.preventDefault();
          dragOver = true;
        }}
        ondragleave={() => (dragOver = false)}
        ondrop={handleFileDrop}
        onclick={() => fileInputEl?.click()}
        onkeydown={(e) => {
          if (e.key === "Enter" || e.key === " ") fileInputEl?.click();
        }}
        style={`border: 2px dashed ${dragOver ? "var(--tandem-accent)" : "var(--tandem-border-strong)"}; border-radius: 6px; padding: 32px 16px; text-align: center; cursor: ${loading ? "wait" : "pointer"}; background: ${dragOver ? "var(--tandem-accent-bg)" : "var(--tandem-surface-muted)"}; transition: border-color 0.15s, background 0.15s;`}
        data-testid="file-upload-zone"
      >
        <input
          bind:this={fileInputEl}
          type="file"
          accept=".md,.txt,.html,.htm,.docx"
          onchange={handleFileSelect}
          style="display: none;"
        />
        <div style="font-size: 13px; color: var(--tandem-fg-muted);">
          {loading ? "Opening..." : "Drop a file here or click to browse"}
        </div>
        <div style="font-size: 11px; color: var(--tandem-fg-subtle); margin-top: 6px;">
          .md, .txt, .html, .docx
        </div>
      </div>
    {/if}

    {#if error}
      <div
        style="margin-top: 10px; padding: 8px 10px; font-size: 12px; color: var(--tandem-error-fg-strong); background: var(--tandem-error-bg); border-radius: 4px; border: 1px solid var(--tandem-error-border);"
        data-testid="file-open-error"
      >
        {error}
      </div>
    {/if}
  </div>
</div>

// src/client/components/FileOpenDialog.tsx
import React, { useCallback, useRef, useState } from "react";
import { API_BASE, readFileForUpload } from "../utils/fileUpload";
import {
  addRecentFile,
  clearRecentFiles,
  loadRecentFiles,
  saveRecentFiles,
} from "../utils/recentFiles";

interface FileOpenDialogProps {
  onClose: () => void;
}

type Mode = "path" | "upload";

export function FileOpenDialog({ onClose }: FileOpenDialogProps) {
  const [mode, setMode] = useState<Mode>("path");
  const [filePath, setFilePath] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [recentFiles, setRecentFiles] = useState<string[]>(loadRecentFiles);

  const pushRecent = useCallback((path: string) => {
    setRecentFiles((prev) => {
      const updated = addRecentFile(prev, path);
      saveRecentFiles(updated);
      return updated;
    });
  }, []);

  const handleClearRecent = useCallback(() => {
    clearRecentFiles();
    setRecentFiles([]);
  }, []);

  const openByPath = useCallback(
    async (pathToOpen: string) => {
      if (loading) return;
      setError(null);
      setLoading(true);
      try {
        const res = await fetch(`${API_BASE}/open`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ filePath: pathToOpen }),
        });
        const data = await res.json();
        if (!res.ok) {
          setError(data.message ?? "Failed to open file");
          return;
        }
        pushRecent(pathToOpen);
        onClose();
      } catch (err) {
        console.error("FileOpenDialog: path open failed", err);
        if (err instanceof SyntaxError) {
          setError("Server returned an unexpected response");
        } else if (err instanceof TypeError) {
          setError("Unexpected response format");
        } else {
          setError("Cannot reach server. Is it running?");
        }
      } finally {
        setLoading(false);
      }
    },
    [loading, onClose, pushRecent],
  );

  const handlePathSubmit = useCallback(() => {
    if (!filePath.trim()) return;
    openByPath(filePath.trim());
  }, [filePath, openByPath]);

  const uploadFile = useCallback(
    async (file: File) => {
      if (loading) return;
      setError(null);
      setLoading(true);
      try {
        const content = await readFileForUpload(file);
        const res = await fetch(`${API_BASE}/upload`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ fileName: file.name, content }),
        });
        const data = await res.json();
        if (!res.ok) {
          setError(data.message ?? "Failed to upload file");
          return;
        }
        onClose();
      } catch (err) {
        console.error("FileOpenDialog: upload failed", err);
        if (err instanceof SyntaxError) {
          setError("Server returned an unexpected response");
        } else if (err instanceof TypeError) {
          setError("Unexpected response format");
        } else {
          setError("Cannot reach server. Is it running?");
        }
      } finally {
        setLoading(false);
      }
    },
    [loading, onClose],
  );

  const handleFileDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragOver(false);
      const file = e.dataTransfer.files[0];
      if (file) uploadFile(file);
    },
    [uploadFile],
  );

  const handleFileSelect = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) uploadFile(file);
    },
    [uploadFile],
  );

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 1000,
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "center",
        paddingTop: "80px",
        background: "rgba(0,0,0,0.3)",
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      onKeyDown={(e) => {
        if (e.key === "Escape") onClose();
      }}
    >
      <div
        style={{
          background: "var(--tandem-surface)",
          borderRadius: "8px",
          boxShadow: "0 8px 30px rgba(0,0,0,0.15)",
          width: "440px",
          padding: "20px",
        }}
        data-testid="file-open-dialog"
      >
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "16px" }}>
          <h3 style={{ margin: 0, fontSize: "15px", fontWeight: 600, color: "var(--tandem-fg)" }}>
            Open File
          </h3>
          <button
            onClick={onClose}
            style={{
              background: "none",
              border: "none",
              cursor: "pointer",
              fontSize: "16px",
              color: "var(--tandem-fg-subtle)",
            }}
          >
            ×
          </button>
        </div>

        {/* Mode toggle */}
        <div style={{ display: "flex", gap: "8px", marginBottom: "16px" }}>
          <button
            onClick={() => setMode("path")}
            style={{
              flex: 1,
              padding: "6px",
              fontSize: "13px",
              border: `1px solid var(--tandem-border)`,
              borderRadius: "4px",
              cursor: "pointer",
              background: mode === "path" ? "var(--tandem-accent)" : "var(--tandem-surface)",
              color: mode === "path" ? "var(--tandem-accent-fg)" : "var(--tandem-fg)",
            }}
          >
            File Path
          </button>
          <button
            onClick={() => setMode("upload")}
            style={{
              flex: 1,
              padding: "6px",
              fontSize: "13px",
              border: `1px solid var(--tandem-border)`,
              borderRadius: "4px",
              cursor: "pointer",
              background: mode === "upload" ? "var(--tandem-accent)" : "var(--tandem-surface)",
              color: mode === "upload" ? "var(--tandem-accent-fg)" : "var(--tandem-fg)",
            }}
          >
            Upload
          </button>
        </div>

        {mode === "path" ? (
          <div>
            <input
              autoFocus
              type="text"
              placeholder="Paste absolute file path..."
              value={filePath}
              onChange={(e) => setFilePath(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handlePathSubmit();
              }}
              style={{
                width: "100%",
                padding: "8px 10px",
                fontSize: "13px",
                border: "1px solid var(--tandem-border-strong)",
                borderRadius: "4px",
                boxSizing: "border-box",
                background: "var(--tandem-surface)",
                color: "var(--tandem-fg)",
              }}
              data-testid="file-path-input"
            />
            <button
              onClick={handlePathSubmit}
              disabled={loading || !filePath.trim()}
              style={{
                marginTop: "10px",
                width: "100%",
                padding: "8px",
                fontSize: "13px",
                fontWeight: 500,
                border: "none",
                borderRadius: "4px",
                cursor: loading ? "wait" : "pointer",
                background: loading ? "var(--tandem-fg-subtle)" : "var(--tandem-accent)",
                color: "var(--tandem-accent-fg)",
                opacity: !filePath.trim() ? 0.5 : 1,
              }}
              data-testid="file-open-submit"
            >
              {loading ? "Opening..." : "Open"}
            </button>

            {/* Recent files */}
            {recentFiles.length > 0 && (
              <div data-testid="recent-files-list" style={{ marginTop: "14px" }}>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: "6px",
                  }}
                >
                  <span
                    style={{
                      fontSize: "11px",
                      color: "var(--tandem-fg-subtle)",
                      textTransform: "uppercase",
                      letterSpacing: "0.05em",
                    }}
                  >
                    Recent
                  </span>
                  <button
                    data-testid="clear-recent-files"
                    onClick={handleClearRecent}
                    type="button"
                    style={{
                      background: "none",
                      border: "none",
                      color: "var(--tandem-fg-subtle)",
                      fontSize: "11px",
                      cursor: "pointer",
                      padding: 0,
                      textDecoration: "underline",
                    }}
                  >
                    Clear all
                  </button>
                </div>
                <div
                  style={{
                    maxHeight: "150px",
                    overflowY: "auto",
                    display: "flex",
                    flexDirection: "column",
                    gap: "2px",
                  }}
                >
                  {recentFiles.map((p, i) => {
                    const parts = p.split(/[/\\]/);
                    const filename = parts.pop() ?? p;
                    const dir = parts.join("/") || "/";
                    return (
                      <button
                        key={p}
                        type="button"
                        data-testid={`recent-file-${i}`}
                        onClick={() => {
                          setFilePath(p);
                          openByPath(p);
                        }}
                        style={{
                          background: "none",
                          border: "none",
                          padding: "6px 8px",
                          borderRadius: "4px",
                          cursor: "pointer",
                          textAlign: "left",
                          display: "flex",
                          flexDirection: "column",
                          gap: "1px",
                        }}
                        onMouseEnter={(e) => {
                          (e.currentTarget as HTMLButtonElement).style.background =
                            "var(--tandem-surface-muted)";
                        }}
                        onMouseLeave={(e) => {
                          (e.currentTarget as HTMLButtonElement).style.background = "transparent";
                        }}
                      >
                        <span style={{ fontSize: "13px", color: "var(--tandem-fg)" }}>{filename}</span>
                        <span
                          style={{
                            fontSize: "11px",
                            color: "var(--tandem-fg-subtle)",
                            overflow: "hidden",
                            textOverflow: "ellipsis",
                            whiteSpace: "nowrap",
                            maxWidth: "380px",
                          }}
                        >
                          {dir}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div
            onDragOver={(e) => {
              e.preventDefault();
              setDragOver(true);
            }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleFileDrop}
            onClick={() => fileInputRef.current?.click()}
            style={{
              border: `2px dashed ${dragOver ? "var(--tandem-accent)" : "var(--tandem-border-strong)"}`,
              borderRadius: "6px",
              padding: "32px 16px",
              textAlign: "center",
              cursor: loading ? "wait" : "pointer",
              background: dragOver ? "var(--tandem-accent-bg)" : "var(--tandem-surface-muted)",
              transition: "border-color 0.15s, background 0.15s",
            }}
            data-testid="file-upload-zone"
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".md,.txt,.html,.htm,.docx"
              onChange={handleFileSelect}
              style={{ display: "none" }}
            />
            <div style={{ fontSize: "13px", color: "var(--tandem-fg-muted)" }}>
              {loading ? "Uploading..." : "Drop a file here or click to browse"}
            </div>
            <div style={{ fontSize: "11px", color: "var(--tandem-fg-subtle)", marginTop: "6px" }}>
              .md, .txt, .html, .docx
            </div>
          </div>
        )}

        {error && (
          <div
            style={{
              marginTop: "10px",
              padding: "8px 10px",
              fontSize: "12px",
              color: "var(--tandem-error-fg-strong)",
              background: "var(--tandem-error-bg)",
              borderRadius: "4px",
              border: "1px solid var(--tandem-error-border)",
            }}
            data-testid="file-open-error"
          >
            {error}
          </div>
        )}
      </div>
    </div>
  );
}
