// src/client/components/SettingsPopover.svelte
<script lang="ts">
import {
  SELECTION_DWELL_MAX_MS,
  SELECTION_DWELL_MIN_MS,
  USER_NAME_MAX_LEN,
} from "../../shared/constants";
import { isTauriRuntime } from "../cowork/cowork-helpers";
import { createAppInfo } from "../hooks/useAppInfo.svelte";
import type { TandemSettings } from "../hooks/useTandemSettings.svelte";
import { createUserName } from "../hooks/useUserName.svelte";
import { API_BASE } from "../utils/fileUpload";
import AccessibilitySettings from "./AccessibilitySettings.svelte";
import AppearanceSettings from "./AppearanceSettings.svelte";
import EditorSettings from "./EditorSettings.svelte";

const HEADING_ID = "tandem-settings-heading";
const FOCUSABLE_SELECTOR =
  'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';
type SettingsSection =
  | "appearance"
  | "editor"
  | "accessibility"
  | "collaboration"
  | "claude-code"
  | "shortcuts"
  | "about";

const SECTIONS: Array<{ id: SettingsSection; label: string }> = [
  { id: "appearance", label: "Appearance" },
  { id: "editor", label: "Editor" },
  { id: "accessibility", label: "Accessibility" },
  { id: "collaboration", label: "Collaboration" },
  { id: "claude-code", label: "Claude Code/Cowork" },
  { id: "shortcuts", label: "Shortcuts" },
  { id: "about", label: "About" },
];

const SHORTCUT_SECTIONS = [
  {
    title: "Editor",
    rows: [
      { keys: "Ctrl+B", description: "Bold" },
      { keys: "Ctrl+I", description: "Italic" },
      { keys: "Ctrl+Z", description: "Undo" },
      { keys: "Ctrl+Y", description: "Redo" },
      { keys: "Ctrl+S", description: "Save document" },
    ],
  },
  {
    title: "General",
    rows: [
      { keys: "Ctrl+,", description: "Open settings" },
      { keys: "?", description: "Show keyboard shortcuts" },
      { keys: "Ctrl+Tab", description: "Next document tab" },
      { keys: "Ctrl+Shift+Tab", description: "Previous document tab" },
    ],
  },
] as const;

interface Props {
  open: boolean;
  onClose: () => void;
  settings: TandemSettings;
  onUpdate: (partial: Partial<TandemSettings>) => void;
  returnFocusEl?: HTMLElement | null;
  anchorEl?: HTMLElement | null;
}

let { open, onClose, settings, onUpdate, returnFocusEl, anchorEl }: Props = $props();

let popoverEl: HTMLDivElement | undefined = $state();
let inputEl: HTMLInputElement | undefined = $state();

const userNameState = createUserName();
let nameInput = $state(userNameState.userName);

const appInfo = createAppInfo(() => open);
let changelogLoading = $state(false);
let changelogError = $state<string | null>(null);
let activeSection = $state<SettingsSection>("appearance");

// Idle-sync: sync only when NOT focused and value differs
$effect(() => {
  const currentUserName = userNameState.userName;
  if (nameInput !== currentUserName && document.activeElement !== inputEl) {
    nameInput = currentUserName;
  }
});

// Initial focus + focus return on close
$effect(() => {
  if (!open) return;
  popoverEl?.focus();
  return () => {
    returnFocusEl?.focus();
  };
});

// Outside-dismiss on pointerdown
$effect(() => {
  if (!open) return;
  const handler = (e: PointerEvent) => {
    const target = e.target as Node;
    if (anchorEl?.contains(target)) return;
    if (popoverEl && !popoverEl.contains(target)) {
      onClose();
    }
  };
  // Defer to avoid immediately firing on the click that opened the popover
  const timer = setTimeout(() => document.addEventListener("pointerdown", handler), 0);
  return () => {
    clearTimeout(timer);
    document.removeEventListener("pointerdown", handler);
  };
});

// Escape to close + focus trap on Tab
$effect(() => {
  if (!open) return;
  const handler = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      onClose();
      return;
    }
    if (e.key !== "Tab" || !popoverEl) return;
    // Re-query focusables on every Tab press (intentional). At the 640px
    // breakpoint the layout reflows from two-column to single-column, which
    // can add or remove scrollable overflow elements — a stale cached list
    // would produce dead-ends in the focus cycle.
    const focusables = popoverEl.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
    if (focusables.length === 0) return;
    const first = focusables[0];
    const last = focusables[focusables.length - 1];
    const active = document.activeElement as HTMLElement | null;
    if (!popoverEl.contains(active)) {
      e.preventDefault();
      first.focus();
      return;
    }
    if (e.shiftKey && active === first) {
      e.preventDefault();
      last.focus();
    } else if (!e.shiftKey && active === last) {
      e.preventDefault();
      first.focus();
    }
  };
  window.addEventListener("keydown", handler);
  return () => window.removeEventListener("keydown", handler);
});

async function handleViewChangelog(): Promise<void> {
  const changelogPath = appInfo.info?.changelogPath;
  if (!changelogPath) {
    changelogError = "Changelog file not found.";
    return;
  }
  changelogLoading = true;
  changelogError = null;
  try {
    const res = await fetch(`${API_BASE}/open`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ filePath: changelogPath, readOnly: true }),
    });
    if (!res.ok) {
      let msg = "Failed to open changelog.";
      try {
        const data = (await res.json()) as { message?: string };
        if (data.message) msg = data.message;
      } catch {
        // ignore JSON parse failure
      }
      if (res.status === 404) msg = "Changelog file not found.";
      changelogError = msg;
      return;
    }
    onClose();
  } catch {
    changelogError = "Server unavailable.";
  } finally {
    changelogLoading = false;
  }
}

const sectionLabelStyle =
  "font-size: 11px; font-weight: 600; color: var(--tandem-fg); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;";

function navButtonStyle(section: SettingsSection): string {
  const active = activeSection === section;
  return [
    "width: 100%;",
    "display: flex;",
    "align-items: center;",
    "min-height: 34px;",
    "padding: 0 var(--tandem-space-3);",
    "border: 1px solid transparent;",
    "border-radius: var(--tandem-r-3);",
    "background: " + (active ? "var(--tandem-accent-bg)" : "transparent") + ";",
    "color: " + (active ? "var(--tandem-accent-fg-strong)" : "var(--tandem-fg-muted)") + ";",
    "font-size: 13px;",
    "font-weight: " + (active ? "600" : "500") + ";",
    "text-align: left;",
    "cursor: pointer;",
  ].join(" ");
}

function panelHeading(section: SettingsSection): string {
  return SECTIONS.find((s) => s.id === section)?.label ?? "Settings";
}

function aboutRows() {
  const info = appInfo.info;
  if (!info) return [];

  const rows: Array<{ label: string; value: string }> = [
    { label: "Version", value: `Tandem v${info.version}` },
    {
      label: "Tools",
      value:
        info.toolCount === null ? "Tool count unavailable" : `${info.toolCount} tools available`,
    },
    { label: "MCP SDK", value: `MCP SDK ${info.mcpSdkVersion}` },
    { label: "Transport", value: info.transport.toUpperCase() },
  ];

  if (info.storagePath) rows.push({ label: "Storage", value: info.storagePath });
  if (info.tokenRotatedAt !== undefined) {
    rows.push({
      label: "Token",
      value:
        info.tokenRotatedAt === null
          ? "Token not created"
          : `Token rotated ${new Date(info.tokenRotatedAt).toLocaleString()}`,
    });
  }
  if (info.changelogPath) rows.push({ label: "Changelog", value: info.changelogPath });

  return rows;
}
</script>

{#if open}
  <div
    aria-hidden="true"
    onclick={onClose}
    style="position: fixed; inset: 0; background: color-mix(in srgb, var(--tandem-bg) 70%, transparent); z-index: 9998;"
  ></div>
  <div
    bind:this={popoverEl}
    data-testid="settings-popover"
    role="dialog"
    aria-modal="true"
    aria-labelledby={HEADING_ID}
    tabindex={-1}
    class="settings-dialog"
  >
    <aside class="settings-sidebar">
      <div style="padding: 0 var(--tandem-space-2);">
        <div id={HEADING_ID} style="font-size: 18px; font-weight: 700; color: var(--tandem-fg);">
          Settings
        </div>
        <div style="margin-top: 2px; font-size: 11px; color: var(--tandem-fg-subtle);">
          Tandem preferences
        </div>
      </div>

      <nav aria-label="Settings sections" style="display: flex; flex-direction: column; gap: 2px;">
        {#each SECTIONS as section (section.id)}
          <button
            type="button"
            aria-current={activeSection === section.id ? "page" : undefined}
            onclick={() => (activeSection = section.id)}
            style={navButtonStyle(section.id)}
          >
            {section.label}
          </button>
        {/each}
      </nav>
    </aside>

    <section class="settings-content" data-testid="settings-content">
      <header
        style="display: flex; align-items: center; justify-content: space-between; min-height: 56px; padding: 0 var(--tandem-space-5); border-bottom: 1px solid var(--tandem-border); background: var(--tandem-surface);"
      >
        <h2 style="font-size: 16px; font-weight: 700; color: var(--tandem-fg); margin: 0;">
          {panelHeading(activeSection)}
        </h2>
        <button
          onclick={onClose}
          style="background: none; border: 1px solid transparent; cursor: pointer; color: var(--tandem-fg-subtle); font-size: 18px; line-height: 1; padding: 4px 8px; min-width: 30px; min-height: 30px; border-radius: var(--tandem-r-2);"
          aria-label="Close settings"
        >
          ×
        </button>
      </header>

      <div style="flex: 1; overflow-y: auto; padding: var(--tandem-space-5);">
        <div style="display: flex; flex-direction: column; gap: var(--tandem-space-5); max-width: 620px;">
          {#if activeSection === "collaboration"}
            <div>
              <label for="settings-display-name" style={sectionLabelStyle}>Display Name</label>
              <input
                bind:this={inputEl}
                id="settings-display-name"
                data-testid="settings-display-name"
                type="text"
                value={nameInput}
                oninput={(e) => { nameInput = (e.target as HTMLInputElement).value; }}
                onblur={() => userNameState.setUserName(nameInput)}
                onkeydown={(e) => {
                  if (e.key === "Enter") (e.currentTarget as HTMLInputElement).blur();
                  if (e.key === "Escape") {
                    nameInput = userNameState.userName;
                    (e.currentTarget as HTMLInputElement).blur();
                  }
                }}
                maxlength={USER_NAME_MAX_LEN}
                style="width: 100%; padding: 8px 10px; font-size: 13px; color: var(--tandem-fg); background: var(--tandem-surface); border: 1px solid var(--tandem-border-strong); border-radius: var(--tandem-r-2); outline: none;"
              />
            </div>

            <div>
              <div id="settings-default-mode-label" style={sectionLabelStyle}>Default Mode</div>
              <div
                role="radiogroup"
                aria-labelledby="settings-default-mode-label"
                style="display: flex; gap: var(--tandem-space-2);"
              >
                <button
                  type="button"
                  data-testid="default-mode-tandem-btn"
                  role="radio"
                  aria-checked={settings.defaultMode === "tandem"}
                  onclick={() => onUpdate({ defaultMode: "tandem" })}
                  style="flex: 1; padding: var(--tandem-space-2); min-height: 30px; border: 2px solid {settings.defaultMode === 'tandem' ? 'var(--tandem-accent)' : 'var(--tandem-border)'}; border-radius: var(--tandem-r-3); background: {settings.defaultMode === 'tandem' ? 'var(--tandem-accent-bg)' : 'var(--tandem-surface)'}; color: {settings.defaultMode === 'tandem' ? 'var(--tandem-accent-fg-strong)' : 'var(--tandem-fg-muted)'}; font-size: 12px; font-weight: {settings.defaultMode === 'tandem' ? 600 : 400}; cursor: pointer;"
                >
                  Tandem
                </button>
                <button
                  type="button"
                  data-testid="default-mode-solo-btn"
                  role="radio"
                  aria-checked={settings.defaultMode === "solo"}
                  onclick={() => onUpdate({ defaultMode: "solo" })}
                  style="flex: 1; padding: var(--tandem-space-2); min-height: 30px; border: 2px solid {settings.defaultMode === 'solo' ? 'var(--tandem-accent)' : 'var(--tandem-border)'}; border-radius: var(--tandem-r-3); background: {settings.defaultMode === 'solo' ? 'var(--tandem-accent-bg)' : 'var(--tandem-surface)'}; color: {settings.defaultMode === 'solo' ? 'var(--tandem-accent-fg-strong)' : 'var(--tandem-fg-muted)'}; font-size: 12px; font-weight: {settings.defaultMode === 'solo' ? 600 : 400}; cursor: pointer;"
                >
                  Solo
                </button>
              </div>
              <div style="font-size: 10px; color: var(--tandem-fg-subtle); margin-top: var(--tandem-space-1);">
                Sets the preferred starting mode for new sessions.
              </div>
            </div>

            <label
              data-testid="solo-rail-hidden-toggle"
              style="display: flex; align-items: center; gap: var(--tandem-space-2); cursor: pointer; font-size: 12px; color: var(--tandem-fg); min-height: 24px;"
            >
              <input
                type="checkbox"
                checked={settings.soloRailHidden}
                onchange={(e) => onUpdate({ soloRailHidden: (e.target as HTMLInputElement).checked })}
                style="accent-color: var(--tandem-accent);"
              />
              <span>Hide side panel in Solo mode</span>
            </label>
            <div style="font-size: 10px; color: var(--tandem-fg-subtle); margin-top: var(--tandem-space-1);">
              When enabled, the annotation panel hides automatically when you enter Solo mode and
              restores when you return to Tandem.
            </div>
          {:else if activeSection === "appearance"}
            <AppearanceSettings {open} {settings} {onUpdate} />
          {:else if activeSection === "editor"}
            <EditorSettings {settings} {onUpdate} />
          {:else if activeSection === "accessibility"}
            <AccessibilitySettings {settings} {onUpdate} />
          {:else if activeSection === "claude-code"}
            <div>
              <div style={sectionLabelStyle}>
                Selection Sensitivity:
                <span style="font-weight: 400; text-transform: none;">
                  {(settings.selectionDwellMs / 1000).toFixed(1)}s
                </span>
              </div>
              <div style="font-size: 10px; color: var(--tandem-fg-subtle); margin-bottom: 6px;">
                How long you must hold a selection before Claude notices it
              </div>
              <input
                data-testid="dwell-time-slider"
                type="range"
                min={SELECTION_DWELL_MIN_MS}
                max={SELECTION_DWELL_MAX_MS}
                step={100}
                value={settings.selectionDwellMs}
                oninput={(e) => onUpdate({ selectionDwellMs: Number((e.target as HTMLInputElement).value) })}
                style="width: 100%; accent-color: var(--tandem-accent);"
                aria-label="Selection dwell time"
              />
              <div style="display: flex; justify-content: space-between; font-size: 10px; color: var(--tandem-fg-subtle);">
                <span>{(SELECTION_DWELL_MIN_MS / 1000).toFixed(1)}s</span>
                <span>{(SELECTION_DWELL_MAX_MS / 1000).toFixed(1)}s</span>
              </div>
            </div>

            <label
              data-testid="selection-toolbar-toggle"
              style="display: flex; align-items: center; gap: var(--tandem-space-2); cursor: pointer; font-size: 12px; color: var(--tandem-fg); min-height: 24px;"
            >
              <input
                type="checkbox"
                checked={settings.selectionToolbar}
                onchange={(e) => onUpdate({ selectionToolbar: (e.target as HTMLInputElement).checked })}
                style="accent-color: var(--tandem-accent);"
              />
              <span>Show floating selection toolbar</span>
            </label>
            {#if isTauriRuntime()}
              {#await import("./CoworkSettings.svelte")}
                <div
                  data-testid="cowork-settings-suspense-fallback"
                  style="font-size: 12px; color: var(--tandem-fg-subtle);"
                >
                  Loading Cowork integration...
                </div>
              {:then mod}
                {@const CoworkSettingsComp = mod.default}
                <CoworkSettingsComp />
              {/await}
            {/if}
          {:else if activeSection === "shortcuts"}
            <div
              data-testid="settings-shortcuts-list"
              style="display: flex; flex-direction: column; gap: var(--tandem-space-4);"
            >
              {#each SHORTCUT_SECTIONS as section (section.title)}
                <section>
                  <div style={sectionLabelStyle}>{section.title}</div>
                  <div style="display: grid; grid-template-columns: minmax(120px, max-content) 1fr; gap: 6px 14px; align-items: center;">
                    {#each section.rows as row (row.keys + row.description)}
                      <kbd style="justify-self: start; padding: 1px 6px; font-family: var(--tandem-font-mono); font-size: 11px; color: var(--tandem-fg); background: var(--tandem-surface-muted); border: 1px solid var(--tandem-border-strong); border-bottom-width: 2px; border-radius: var(--tandem-r-2);">
                        {row.keys}
                      </kbd>
                      <span style="font-size: 13px; color: var(--tandem-fg-muted);">{row.description}</span>
                    {/each}
                  </div>
                </section>
              {/each}
            </div>
          {:else}
            <div>
              <button
                data-testid="view-changelog-btn"
                onclick={() => void handleViewChangelog()}
                disabled={changelogLoading || appInfo.loading}
                style="width: 100%; padding: var(--tandem-space-2); font-size: 13px; font-weight: 500; border: 1px solid var(--tandem-border-strong); border-radius: var(--tandem-r-2); cursor: {changelogLoading || appInfo.loading ? 'not-allowed' : 'pointer'}; background: var(--tandem-surface-muted); color: var(--tandem-fg); opacity: {changelogLoading || appInfo.loading ? 0.6 : 1};"
              >
                {changelogLoading ? "Opening…" : "View Changelog"}
              </button>
              {#if changelogError}
                <div style="margin-top: 6px; font-size: 11px; color: var(--tandem-error-fg);">
                  {changelogError}
                </div>
              {/if}
            </div>

            <div>
              <a
                href="https://github.com/bloknayrb/tandem/issues/new"
                target="_blank"
                rel="noreferrer"
                style="display: block; width: 100%; padding: var(--tandem-space-2); font-size: 13px; font-weight: 500; border: 1px solid var(--tandem-border-strong); border-radius: var(--tandem-r-2); background: var(--tandem-surface-muted); color: var(--tandem-fg); text-align: center; text-decoration: none; box-sizing: border-box;"
              >
                Report a bug
              </a>
            </div>

            <div
              data-testid="app-info-footer"
              style="border-top: 1px solid var(--tandem-border); padding-top: 10px;"
            >
              <div style={sectionLabelStyle}>About</div>
              {#if appInfo.loading}
                <div style="font-size: 11px; color: var(--tandem-fg-subtle);">Loading...</div>
              {:else if appInfo.info}
                <dl style="display: grid; grid-template-columns: max-content minmax(0, 1fr); gap: 5px 12px; margin: 0; font-size: 11px;">
                  {#each aboutRows() as row (row.label)}
                    <dt style="color: var(--tandem-fg-subtle);">{row.label}</dt>
                    <dd style="margin: 0; color: var(--tandem-fg-muted); overflow-wrap: anywhere;">{row.value}</dd>
                  {/each}
                </dl>
              {:else}
                <div style="font-size: 11px; color: var(--tandem-fg-subtle);">App info unavailable.</div>
              {/if}
            </div>
          {/if}
        </div>
      </div>
    </section>
  </div>
{/if}

<style>
  .settings-dialog {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: min(900px, calc(100vw - 32px));
    height: min(680px, calc(100vh - 32px));
    background: var(--tandem-surface);
    color: var(--tandem-fg);
    border: 1px solid var(--tandem-border);
    border-radius: var(--tandem-r-4);
    box-shadow: var(--tandem-shadow-3);
    z-index: 9999;
    display: grid;
    grid-template-columns: 188px minmax(0, 1fr);
    outline: none;
    overflow: hidden;
  }

  .settings-sidebar {
    display: flex;
    flex-direction: column;
    gap: var(--tandem-space-4);
    padding: var(--tandem-space-5) var(--tandem-space-3);
    border-right: 1px solid var(--tandem-border);
    background: var(--tandem-surface-muted);
    overflow-y: auto;
  }

  .settings-content {
    display: flex;
    flex-direction: column;
    min-width: 0;
    min-height: 0;
  }

  @media (max-width: 640px) {
    .settings-dialog {
      grid-template-columns: 1fr;
      grid-template-rows: minmax(auto, 45%) 1fr;
    }

    .settings-sidebar {
      border-right: none;
      border-bottom: 1px solid var(--tandem-border);
      padding: var(--tandem-space-3);
    }
  }
</style>

// src/client/components/SettingsPopover.tsx
import React, { lazy, Suspense, useEffect, useRef, useState } from "react";
import {
  SELECTION_DWELL_MAX_MS,
  SELECTION_DWELL_MIN_MS,
  USER_NAME_MAX_LEN,
} from "../../shared/constants";
import { isTauriRuntime } from "../cowork/cowork-helpers";
import { useAppInfo } from "../hooks/useAppInfo";
import type { TandemSettings } from "../hooks/useTandemSettings";
import { useUserName } from "../hooks/useUserName";
import { AccessibilitySettings } from "./AccessibilitySettings";
import { AppearanceSettings } from "./AppearanceSettings";
import { EditorSettings } from "./EditorSettings";
import { sectionLabelStyle } from "./settingsStyles";

// Lazy-imported so non-Tauri bundles defer loading the Cowork code path and
// so the popover's initial render stays cheap.
const CoworkSettings = lazy(() =>
  import("./CoworkSettings").then((m) => ({ default: m.CoworkSettings })),
);

interface SettingsPopoverProps {
  open: boolean;
  onClose: () => void;
  settings: TandemSettings;
  onUpdate: (partial: Partial<TandemSettings>) => void;
  /** Element to return focus to on close (typically the settings gear button). */
  returnFocusRef?: React.RefObject<HTMLElement | null>;
  /**
   * Element that toggles the popover. Excluded from outside-click detection
   * so the anchor's own click handler (not the dismiss logic) controls
   * close-while-open.
   */
  anchorRef?: React.RefObject<HTMLElement | null>;
}

const POPOVER_WIDTH = 320;
const HEADING_ID = "tandem-settings-heading";

const FOCUSABLE_SELECTOR =
  'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

export function SettingsPopover({
  open,
  onClose,
  settings,
  onUpdate,
  returnFocusRef,
  anchorRef,
}: SettingsPopoverProps) {
  const popoverRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const { userName, setUserName } = useUserName();
  const [nameInput, setNameInput] = useState(userName);
  const { info: appInfo, loading: appInfoLoading } = useAppInfo(open);

  // Idle-sync: commit c9a63de dropped the always-sync effect because it
  // clobbered in-progress edits. This version syncs only when the input
  // is NOT focused and the value actually differs — so cross-surface
  // changes propagate, but typing is never interrupted.
  useEffect(() => {
    if (nameInput !== userName && document.activeElement !== inputRef.current) {
      setNameInput(userName);
    }
  }, [userName, nameInput]);

  // Initial focus + focus return on close
  useEffect(() => {
    if (!open) return;
    // Focus the dialog container so screen readers announce the heading;
    // Tab then moves into the content.
    const node = popoverRef.current;
    node?.focus();
    return () => {
      returnFocusRef?.current?.focus();
    };
  }, [open, returnFocusRef]);

  // Outside-dismiss on pointerdown (covers mouse + touch + pen)
  useEffect(() => {
    if (!open) return;
    const handler = (e: PointerEvent) => {
      const target = e.target as Node;
      // Let the anchor's own click handler toggle the popover — otherwise the
      // pointerdown-outside close races with the click-reopen and the popover
      // re-opens immediately.
      if (anchorRef?.current?.contains(target)) return;
      if (popoverRef.current && !popoverRef.current.contains(target)) {
        onClose();
      }
    };
    const timer = setTimeout(() => document.addEventListener("pointerdown", handler), 0);
    return () => {
      clearTimeout(timer);
      document.removeEventListener("pointerdown", handler);
    };
  }, [open, onClose, anchorRef]);

  // Escape to close + focus trap on Tab
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose();
        return;
      }
      if (e.key !== "Tab" || !popoverRef.current) return;
      const focusables = popoverRef.current.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
      if (focusables.length === 0) return;
      const first = focusables[0];
      const last = focusables[focusables.length - 1];
      const active = document.activeElement as HTMLElement | null;
      // If focus has escaped the dialog entirely, pull it back in.
      if (!popoverRef.current.contains(active)) {
        e.preventDefault();
        first.focus();
        return;
      }
      if (e.shiftKey && active === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && active === last) {
        e.preventDefault();
        first.focus();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      ref={popoverRef}
      data-testid="settings-popover"
      role="dialog"
      aria-modal="true"
      aria-labelledby={HEADING_ID}
      tabIndex={-1}
      style={{
        position: "fixed",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        maxHeight: "calc(100vh - 32px)",
        overflowY: "auto",
        width: `${POPOVER_WIDTH}px`,
        background: "var(--tandem-surface)",
        color: "var(--tandem-fg)",
        border: "1px solid var(--tandem-border)",
        borderRadius: "8px",
        boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
        padding: "16px",
        zIndex: 9999,
        display: "flex",
        flexDirection: "column",
        gap: "14px",
        outline: "none",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <span
          id={HEADING_ID}
          style={{ fontSize: "13px", fontWeight: 600, color: "var(--tandem-fg)" }}
        >
          Settings
        </span>
        <button
          onClick={onClose}
          style={{
            background: "none",
            border: "none",
            cursor: "pointer",
            color: "var(--tandem-fg-subtle)",
            fontSize: "16px",
            lineHeight: 1,
            padding: "4px 6px",
            minWidth: "24px",
            minHeight: "24px",
          }}
          aria-label="Close settings"
        >
          {"×"}
        </button>
      </div>

      {/* Display Name */}
      <div>
        <label htmlFor="settings-display-name" style={sectionLabelStyle}>
          Display Name
        </label>
        <input
          ref={inputRef}
          id="settings-display-name"
          data-testid="settings-display-name"
          type="text"
          value={nameInput}
          onChange={(e) => setNameInput(e.target.value)}
          onBlur={() => setUserName(nameInput)}
          onKeyDown={(e) => {
            if (e.key === "Enter") e.currentTarget.blur();
            if (e.key === "Escape") {
              setNameInput(userName);
              e.currentTarget.blur();
            }
          }}
          maxLength={USER_NAME_MAX_LEN}
          style={{
            width: "100%",
            padding: "6px 8px",
            fontSize: "12px",
            color: "var(--tandem-fg)",
            background: "var(--tandem-surface)",
            border: "1px solid var(--tandem-border-strong)",
            borderRadius: "4px",
            outline: "none",
          }}
        />
      </div>

      {/* Appearance: Theme, Layout, Primary Tab/Panel Order, Text Size, Reduce Motion */}
      <AppearanceSettings open={open} settings={settings} onUpdate={onUpdate} />

      {/* Editor Width */}
      <EditorSettings settings={settings} onUpdate={onUpdate} />

      {/* Authorship */}
      <AccessibilitySettings settings={settings} onUpdate={onUpdate} />

      {/* Selection sensitivity (dwell time) */}
      <div>
        <div style={sectionLabelStyle}>
          Selection Sensitivity:{" "}
          <span style={{ fontWeight: 400, textTransform: "none" }}>
            {(settings.selectionDwellMs / 1000).toFixed(1)}s
          </span>
        </div>
        <div style={{ fontSize: "10px", color: "var(--tandem-fg-subtle)", marginBottom: "6px" }}>
          How long you must hold a selection before Claude notices it
        </div>
        <input
          data-testid="dwell-time-slider"
          type="range"
          min={SELECTION_DWELL_MIN_MS}
          max={SELECTION_DWELL_MAX_MS}
          step={100}
          value={settings.selectionDwellMs}
          onChange={(e) => onUpdate({ selectionDwellMs: Number(e.target.value) })}
          style={{ width: "100%", accentColor: "var(--tandem-accent)" }}
          aria-label="Selection dwell time"
        />
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            fontSize: "10px",
            color: "var(--tandem-fg-subtle)",
          }}
        >
          <span>{(SELECTION_DWELL_MIN_MS / 1000).toFixed(1)}s</span>
          <span>{(SELECTION_DWELL_MAX_MS / 1000).toFixed(1)}s</span>
        </div>
      </div>

      {/* Cowork integration — Tauri desktop only (CLI / pure web callers don't
          have the invoke surface PR e ships). */}
      {isTauriRuntime() && (
        <Suspense
          fallback={
            <div
              data-testid="cowork-settings-suspense-fallback"
              style={{ fontSize: 12, color: "var(--tandem-fg-subtle)" }}
            >
              Loading Cowork integration...
            </div>
          }
        >
          <CoworkSettings />
        </Suspense>
      )}

      {/* App version footer — read-only metadata. Hidden on error (graceful
          degradation); shown as "Loading..." until the /api/info fetch
          completes. */}
      {(appInfoLoading || appInfo !== null) && (
        <div
          data-testid="app-info-footer"
          style={{
            borderTop: "1px solid var(--tandem-border)",
            paddingTop: "10px",
          }}
        >
          <div style={sectionLabelStyle}>About</div>
          {appInfoLoading ? (
            <div style={{ fontSize: "11px", color: "var(--tandem-fg-subtle)" }}>Loading...</div>
          ) : (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "3px",
                fontSize: "11px",
                color: "var(--tandem-fg-subtle)",
              }}
            >
              <span>Tandem v{appInfo?.version}</span>
              <span>MCP SDK {appInfo?.mcpSdkVersion}</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
