// src/client/status/StatusBar.svelte
<script lang="ts">
import { untrack } from "svelte";
import { USER_NAME_MAX_LEN } from "../../shared/constants";
import { createUserName } from "../hooks/useUserName.svelte";
import type { ConnectionStatus } from "../hooks/yjsSync.svelte";

interface Props {
  connected: boolean;
  connectionStatus: ConnectionStatus;
  reconnectAttempts: number;
  disconnectedSince: number | null;
  claudeStatus: string | null;
  claudeActive: boolean;
  readOnly?: boolean;
  documentCount?: number;
  saving?: boolean;
  heldCount?: number;
  mode?: import("../../shared/types").TandemMode;
  onShowHeld?: () => void;
}

let {
  connected,
  connectionStatus,
  reconnectAttempts,
  disconnectedSince,
  claudeStatus,
  claudeActive,
  readOnly,
  documentCount = 0,
  saving = false,
  heldCount,
  mode,
  onShowHeld,
}: Props = $props();

const RECONNECTED_FLASH_MS = 2_000;

const userNameState = createUserName();
let nameInput = $state(userNameState.userName);
let inputEl: HTMLInputElement | undefined = $state();

// Idle-sync: sync only when NOT focused and value differs
$effect(() => {
  const currentUserName = userNameState.userName;
  if (nameInput !== currentUserName && document.activeElement !== inputEl) {
    nameInput = currentUserName;
  }
});

let showReconnectedFlash = $state(false);
let elapsedSeconds = $state(0);
// intentional snapshot — updated inside $effect to detect rising-edge reconnect
let prevConnected = untrack(() => connected);

$effect(() => {
  const was = prevConnected;
  prevConnected = connected;
  if (connected && !was) {
    showReconnectedFlash = true;
    const timer = setTimeout(() => {
      showReconnectedFlash = false;
    }, RECONNECTED_FLASH_MS);
    return () => clearTimeout(timer);
  }
});

// Tick elapsed time while disconnected
$effect(() => {
  if (disconnectedSince == null) {
    elapsedSeconds = 0;
    return;
  }
  elapsedSeconds = Math.floor((Date.now() - disconnectedSince) / 1000);
  const interval = setInterval(() => {
    elapsedSeconds = Math.floor((Date.now() - (disconnectedSince ?? 0)) / 1000);
  }, 1000);
  return () => clearInterval(interval);
});

const isReconnecting = $derived(connectionStatus === "connecting");
const dotColor = $derived(
  connected
    ? "var(--tandem-success)"
    : isReconnecting
      ? "var(--tandem-warning)"
      : "var(--tandem-error)",
);

const connLabel = $derived(
  showReconnectedFlash
    ? "Reconnected"
    : connectionStatus === "connected"
      ? "Connected"
      : connectionStatus === "connecting"
        ? (() => {
            const parts = ["Reconnecting…"];
            if (reconnectAttempts > 0 || elapsedSeconds > 0) {
              const details: string[] = [];
              if (reconnectAttempts > 0) details.push(`attempt ${reconnectAttempts}`);
              if (elapsedSeconds > 0) details.push(`${elapsedSeconds}s`);
              parts.push(`(${details.join(", ")})`);
            }
            return parts.join(" ");
          })()
        : "Disconnected — check that the server is running",
);

function commitName() {
  userNameState.setUserName(nameInput);
}
</script>

<div
  style="display: flex; align-items: center; justify-content: space-between; padding: 0 var(--tandem-space-4); height: 28px; border-top: 1px solid var(--tandem-border); background: var(--tandem-surface-muted); font-family: var(--tandem-font-mono); font-size: var(--tandem-text-xs); color: var(--tandem-fg-muted); user-select: none; gap: var(--tandem-space-3);"
>
  <div style="display: flex; align-items: center; gap: var(--tandem-space-2);">
    <span
      class="status-dot"
      style="width: 8px; height: 8px; border-radius: 50%; background: {dotColor}; display: inline-block; animation: {isReconnecting ? 'tandem-reconnect-pulse 1.2s ease-in-out infinite' : 'none'};"
    ></span>
    <span>{connLabel}</span>
    {#if documentCount > 0}
      <span style="color: var(--tandem-fg-subtle);">
        {documentCount} doc{documentCount !== 1 ? "s" : ""} open
      </span>
    {/if}
    {#if saving}
      <span
        data-testid="save-indicator"
        style="color: var(--tandem-accent);"
      >
        Saving...
      </span>
    {/if}
  </div>

  <div style="display: flex; align-items: center; gap: var(--tandem-space-1); font-size: var(--tandem-text-xs); color: var(--tandem-fg-subtle);">
    <span>You:</span>
    <input
      bind:this={inputEl}
      data-testid="user-name-input"
      type="text"
      value={nameInput}
      oninput={(e) => { nameInput = (e.target as HTMLInputElement).value; }}
      onblur={commitName}
      onkeydown={(e) => {
        if (e.key === "Enter") (e.currentTarget as HTMLInputElement).blur();
        if (e.key === "Escape") {
          nameInput = userNameState.userName;
          (e.currentTarget as HTMLInputElement).blur();
        }
      }}
      aria-label="Display name"
      title="Your display name"
      maxlength={USER_NAME_MAX_LEN}
      style="background: transparent; border: none; border-bottom: 1px dashed transparent; color: var(--tandem-fg-muted); font: inherit; font-family: var(--tandem-font-sans); font-size: var(--tandem-text-xs); width: 80px; outline: none; padding: 0 2px;"
    />
  </div>

  {#if (heldCount ?? 0) > 0 && mode === "solo"}
    <button
      data-testid="sb-held"
      onclick={onShowHeld}
      title="Show held annotations — switches to Tandem"
      style="display: inline-flex; align-items: center; gap: var(--tandem-space-1); padding: 1px 8px; font-size: var(--tandem-text-xs); font-weight: 600; border: 1px solid var(--tandem-warning-border); border-radius: var(--tandem-r-pill); background: var(--tandem-warning-bg); color: var(--tandem-warning-fg-strong); cursor: pointer;"
    >
      <span style="width: 6px; height: 6px; border-radius: 50%; background: var(--tandem-warning-fg-strong); display: inline-block;"></span>
      {heldCount} held
    </button>
  {/if}

  {#if readOnly}
    <span
      style="padding: 1px 8px; font-size: var(--tandem-text-2xs); font-weight: 600; color: var(--tandem-warning-fg-strong); background: var(--tandem-warning-bg); border-radius: var(--tandem-r-pill); border: 1px solid var(--tandem-warning-border);"
    >
      Review Only
    </span>
  {/if}

  <div style="display: flex; align-items: center; gap: var(--tandem-space-2);">
    <span
      class="claude-dot"
      style="width: 8px; height: 8px; border-radius: 50%; background: var(--tandem-author-claude); opacity: {claudeActive ? 1 : 0.4}; display: inline-block; transition: opacity 0.3s ease; animation: {claudeActive ? 'tandem-status-pulse 1.5s ease-in-out infinite' : 'none'};"
    ></span>
    <span style="transition: color 0.3s ease; color: {claudeActive ? 'var(--tandem-fg)' : 'var(--tandem-fg-subtle)'};">
      {claudeStatus ? `Claude · ${claudeStatus}` : "Claude · idle"}
    </span>
  </div>
</div>

<style>
  :global {
    @keyframes tandem-status-pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }
    @keyframes tandem-reconnect-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.3; } }
  }

  @media (forced-colors: active) {
    .status-dot,
    .claude-dot {
      outline: 1px solid ButtonText;
      outline-offset: 1px;
    }
  }
</style>

// src/client/status/StatusBar.tsx
import React, { useEffect, useRef, useState } from "react";
import { CLAUDE_PRESENCE_COLOR, USER_NAME_KEY, USER_NAME_DEFAULT } from "../../shared/constants";
import type { TandemMode } from "../../shared/types";
import type { ConnectionStatus } from "../hooks/useYjsSync";

interface StatusBarProps {
  connected: boolean;
  connectionStatus: ConnectionStatus;
  reconnectAttempts: number;
  disconnectedSince: number | null;
  claudeStatus: string | null;
  claudeActive: boolean;
  readOnly?: boolean;
  documentCount?: number;
  tandemMode: TandemMode;
  onModeChange: (mode: TandemMode) => void;
  heldCount: number;
}

const RECONNECTED_FLASH_MS = 2_000;

export function StatusBar({
  connected,
  connectionStatus,
  reconnectAttempts,
  disconnectedSince,
  claudeStatus,
  claudeActive,
  readOnly,
  documentCount = 0,
  tandemMode,
  onModeChange,
  heldCount,
}: StatusBarProps) {
  const [userName, setUserName] = useState(() => {
    try {
      return localStorage.getItem(USER_NAME_KEY)?.trim() || USER_NAME_DEFAULT;
    } catch {
      return USER_NAME_DEFAULT;
    }
  });
  const [nameInput, setNameInput] = useState(userName);
  const commitName = () => {
    const trimmed = nameInput.trim() || USER_NAME_DEFAULT;
    setUserName(trimmed);
    setNameInput(trimmed);
    try {
      localStorage.setItem(USER_NAME_KEY, trimmed);
    } catch {
      // localStorage unavailable (incognito/storage-disabled)
    }
  };
  const [showReconnectedFlash, setShowReconnectedFlash] = useState(false);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const prevConnected = useRef(connected);

  useEffect(() => {
    const was = prevConnected.current;
    prevConnected.current = connected;
    if (connected && !was) {
      setShowReconnectedFlash(true);
      const timer = setTimeout(() => setShowReconnectedFlash(false), RECONNECTED_FLASH_MS);
      return () => clearTimeout(timer);
    }
  }, [connected]);

  // Tick elapsed time while disconnected
  useEffect(() => {
    if (disconnectedSince == null) {
      setElapsedSeconds(0);
      return;
    }
    // Set initial value immediately
    setElapsedSeconds(Math.floor((Date.now() - disconnectedSince) / 1000));
    const interval = setInterval(() => {
      setElapsedSeconds(Math.floor((Date.now() - disconnectedSince) / 1000));
    }, 1000);
    return () => clearInterval(interval);
  }, [disconnectedSince]);

  const isReconnecting = connectionStatus === "connecting";
  const dotColor = connected ? "#22c55e" : isReconnecting ? "#eab308" : "#ef4444";

  let connLabel: string;
  if (showReconnectedFlash) {
    connLabel = "Reconnected";
  } else if (connectionStatus === "connected") {
    connLabel = "Connected";
  } else if (connectionStatus === "connecting") {
    const parts = ["Reconnecting\u2026"];
    if (reconnectAttempts > 0 || elapsedSeconds > 0) {
      const details: string[] = [];
      if (reconnectAttempts > 0) details.push(`attempt ${reconnectAttempts}`);
      if (elapsedSeconds > 0) details.push(`${elapsedSeconds}s`);
      parts.push(`(${details.join(", ")})`);
    }
    connLabel = parts.join(" ");
  } else {
    connLabel = "Disconnected \u2014 check that the server is running";
  }

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "4px 16px",
        height: "28px",
        borderTop: "1px solid #e5e7eb",
        background: "#fafafa",
        fontSize: "12px",
        color: "#6b7280",
        userSelect: "none",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
        <span
          style={{
            width: "8px",
            height: "8px",
            borderRadius: "50%",
            background: dotColor,
            display: "inline-block",
            animation: isReconnecting ? "tandem-reconnect-pulse 1.2s ease-in-out infinite" : "none",
          }}
        />
        <span>{connLabel}</span>
        {documentCount > 0 && (
          <span style={{ color: "#9ca3af" }}>
            {documentCount} doc{documentCount !== 1 ? "s" : ""} open
          </span>
        )}
      </div>

      {/* Mode switcher */}
      <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
        {heldCount > 0 && (
          <span
            style={{
              padding: "1px 6px",
              fontSize: "10px",
              fontWeight: 600,
              color: "#92400e",
              background: "#fef3c7",
              borderRadius: "9999px",
            }}
          >
            {heldCount} held
          </span>
        )}
        <div
          style={{
            display: "flex",
            border: "1px solid #d1d5db",
            borderRadius: "4px",
            overflow: "hidden",
          }}
        >
          <button
            title="Write undisturbed — Claude only responds when you message"
            onClick={() => onModeChange("solo")}
            style={{
              padding: "1px 8px",
              fontSize: "11px",
              border: "none",
              borderRight: "1px solid #d1d5db",
              cursor: "pointer",
              background: tandemMode === "solo" ? "#6366f1" : "transparent",
              color: tandemMode === "solo" ? "#fff" : "#6b7280",
              fontWeight: tandemMode === "solo" ? 600 : 400,
            }}
          >
            Solo
          </button>
          <button
            title="Full collaboration — Claude reacts to selections and document changes"
            onClick={() => onModeChange("tandem")}
            style={{
              padding: "1px 8px",
              fontSize: "11px",
              border: "none",
              cursor: "pointer",
              background: tandemMode === "tandem" ? "#6366f1" : "transparent",
              color: tandemMode === "tandem" ? "#fff" : "#6b7280",
              fontWeight: tandemMode === "tandem" ? 600 : 400,
            }}
          >
            Tandem
          </button>
        </div>
        <span style={{ display: "flex", alignItems: "center", gap: "4px", fontSize: "11px" }}>
          <span
            style={{
              width: "6px",
              height: "6px",
              borderRadius: "50%",
              background: tandemMode === "tandem" ? "#22c55e" : "#9ca3af",
              display: "inline-block",
            }}
          />
          <span style={{ color: "#9ca3af" }}>
            {tandemMode === "tandem" ? "Claude is active" : "Claude is listening"}
          </span>
        </span>
      </div>

      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "4px",
          fontSize: "11px",
          color: "#9ca3af",
        }}
      >
        <span>You:</span>
        <input
          data-testid="user-name-input"
          type="text"
          value={nameInput}
          onChange={(e) => setNameInput(e.target.value)}
          onBlur={commitName}
          onKeyDown={(e) => {
            if (e.key === "Enter") e.currentTarget.blur();
            if (e.key === "Escape") {
              setNameInput(userName);
              e.currentTarget.blur();
            }
          }}
          aria-label="Display name"
          title="Your display name (updates on next tab switch or refresh)"
          maxLength={40}
          style={{
            background: "transparent",
            border: "none",
            borderBottom: "1px solid #e5e7eb",
            color: "#6b7280",
            fontSize: "11px",
            width: "80px",
            outline: "none",
            padding: "0 2px",
          }}
        />
      </div>
      {readOnly && (
        <span
          style={{
            padding: "1px 8px",
            fontSize: "11px",
            fontWeight: 600,
            color: "#92400e",
            background: "#fef3c7",
            borderRadius: "9999px",
            border: "1px solid #fde68a",
          }}
        >
          Review Only
        </span>
      )}
      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
        <span
          style={{
            width: "8px",
            height: "8px",
            borderRadius: "50%",
            background: CLAUDE_PRESENCE_COLOR,
            opacity: claudeActive ? 1 : 0.4,
            display: "inline-block",
            transition: "opacity 0.3s ease",
            animation: claudeActive ? "tandem-status-pulse 1.5s ease-in-out infinite" : "none",
          }}
        />
        <span
          style={{ transition: "color 0.3s ease", color: claudeActive ? "#4b5563" : "#9ca3af" }}
        >
          {claudeStatus ? `Claude -- ${claudeStatus}` : "Claude -- idle"}
        </span>
      </div>
      <style>{`
        @keyframes tandem-status-pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }
        @keyframes tandem-reconnect-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.3; } }
      `}</style>
    </div>
  );
}
