// src/client/tabs/DocumentTabs.svelte
<script lang="ts">
import { API_OPEN } from "../../shared/api-paths.js";
import { createScratchpad } from "../actions/builtin.svelte.js";
import FileOpenDialog from "../components/FileOpenDialog.svelte";
import type { OpenTab } from "../types.js";
import { API_BASE } from "../utils/fileUpload.js";
import { addRecentFile, loadRecentFilesCached, saveRecentFiles } from "../utils/recentFiles.js";
import NewTabMenu from "./NewTabMenu.svelte";
import TabItem from "./TabItem.svelte";

interface Props {
  tabs: OpenTab[];
  activeTabId: string | null;
  onTabSwitch: (tabId: string) => void;
  onTabClose: (tabId: string) => void;
  reorder?: (fromId: string, toId: string, side?: "left" | "right") => void;
  reduceMotion?: boolean;
}

const {
  tabs,
  activeTabId,
  onTabSwitch,
  onTabClose,
  reorder,
  reduceMotion = false,
}: Props = $props();

const scrollBehavior: ScrollBehavior = $derived(reduceMotion ? "auto" : "smooth");

let showDialog = $state(false);
let showRecent = $state(false);
let recentFiles = $state<string[]>([]);
let openBtnEl: HTMLButtonElement | null = $state(null);

// Plain let — not reactive UI; just internal close-dedup guard
let closingIds = new Set<string>();

// Clean up stale entries when tabs change (closed tab removed from DOM)
$effect(() => {
  const currentIds = new Set(tabs.map((t) => t.id));
  for (const id of closingIds) {
    if (!currentIds.has(id)) closingIds.delete(id);
  }
});

function guardedClose(tabId: string) {
  if (closingIds.has(tabId)) return;
  closingIds.add(tabId);
  onTabClose(tabId);
}

let scrollEl: HTMLDivElement | undefined = $state();
let canScrollLeft = $state(false);
let canScrollRight = $state(false);
let draggedId = $state<string | null>(null);
let dropTarget = $state<{ id: string; side: "left" | "right" } | null>(null);

function clearDragState() {
  draggedId = null;
  dropTarget = null;
}

function updateScrollState() {
  const el = scrollEl;
  if (!el) return;
  canScrollLeft = el.scrollLeft > 0;
  canScrollRight = el.scrollLeft + el.clientWidth < el.scrollWidth - 1;
}

// Set up scroll listeners and resize observer
$effect(() => {
  const el = scrollEl;
  if (!el) return;
  updateScrollState();
  el.addEventListener("scroll", updateScrollState, { passive: true });
  const observer = new ResizeObserver(updateScrollState);
  observer.observe(el);
  return () => {
    el.removeEventListener("scroll", updateScrollState);
    observer.disconnect();
  };
});

// Re-check overflow when tabs change
$effect(() => {
  // Track tabs.length
  void tabs.length;
  updateScrollState();
});

// Auto-scroll active tab into view
$effect(() => {
  if (!activeTabId || !scrollEl) return;
  const el = scrollEl.querySelector(`[data-testid="tab-${activeTabId}"]`);
  if (el) {
    (el as HTMLElement).scrollIntoView({
      inline: "nearest",
      block: "nearest",
      behavior: scrollBehavior,
    });
  }
});

// Clear drag state when tab list changes mid-drag
$effect(() => {
  void tabs.length;
  clearDragState();
});

// DnD handlers
function handleDragStart(e: DragEvent, id: string) {
  draggedId = id;
  if (e.dataTransfer) {
    e.dataTransfer.setData("text/plain", id);
    e.dataTransfer.effectAllowed = "move";
  }
}

function handleDragOver(e: DragEvent, id: string) {
  e.preventDefault();
  if (!draggedId || draggedId === id) {
    dropTarget = null;
    return;
  }
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
  const midX = rect.left + rect.width / 2;
  const side = e.clientX < midX ? "left" : "right";
  dropTarget = { id, side };
}

function handleDrop(e: DragEvent, targetId: string) {
  e.preventDefault();
  const fromId = e.dataTransfer?.getData("text/plain");
  if (fromId && fromId !== targetId && reorder) {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    const midX = rect.left + rect.width / 2;
    const side = e.clientX < midX ? "left" : "right";
    reorder(fromId, targetId, side);
  }
  clearDragState();
}

function handleDragEnd() {
  clearDragState();
}

function handleDragLeave() {
  dropTarget = null;
}

// Keyboard reordering (Alt+Arrow swaps with neighbor)
function handleKeyDown(e: KeyboardEvent, id: string) {
  if (!e.altKey || !reorder) return;
  if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") return;
  e.preventDefault();

  const idx = tabs.findIndex((t) => t.id === id);
  if (idx === -1) return;

  if (e.key === "ArrowLeft" && idx > 0) {
    reorder(id, tabs[idx - 1].id);
  } else if (e.key === "ArrowRight" && idx < tabs.length - 1) {
    reorder(tabs[idx + 1].id, id);
  }
}

function scrollLeft() {
  scrollEl?.scrollBy({ left: -150, behavior: scrollBehavior });
}

function scrollRight() {
  scrollEl?.scrollBy({ left: 150, behavior: scrollBehavior });
}

const singleTab = $derived(tabs.length <= 1);

$effect(() => {
  if (!showRecent) return;

  function handlePointerDown(e: PointerEvent) {
    const target = e.target as Node | null;
    if (!target) return;
    if (openBtnEl?.contains(target)) return;
    if ((target as Element).closest?.(".new-tab-menu")) return;
    if ((target as Element).closest?.("[data-tauri-drag-region]")) return;
    showRecent = false;
  }

  window.addEventListener("pointerdown", handlePointerDown, true);
  return () => window.removeEventListener("pointerdown", handlePointerDown, true);
});
</script>

<div
  style="position: relative; display: flex; align-items: stretch; background: var(--tandem-surface-muted); border-bottom: 1px solid var(--tandem-border); min-height: 32px; padding: 0 var(--tandem-space-3); z-index: var(--tandem-z-base);"
>
  {#if canScrollLeft}
    <button
      data-testid="tab-scroll-left"
      onclick={scrollLeft}
      style="display: flex; align-items: center; justify-content: center; width: 28px; min-width: 28px; background: linear-gradient(to right, var(--tandem-surface-muted) 70%, transparent); border: none; cursor: pointer; font-size: 12px; color: var(--tandem-fg-muted); padding: 0; z-index: 1;"
      title="Scroll tabs left"
    >
      ◀
    </button>
  {/if}

  <div
    bind:this={scrollEl}
    data-testid="tab-scroll-container"
    class="tab-scroll-hide"
    role="tablist"
    aria-label="Open documents"
    style="display: flex; align-items: stretch; gap: 2px; flex: 1; overflow-x: auto; overflow-y: hidden;"
  >
    {#each tabs as tab (tab.id)}
      <TabItem
        {tab}
        isActive={tab.id === activeTabId}
        onswitch={onTabSwitch}
        onclose={guardedClose}
        draggable={!singleTab}
        ondragstart={handleDragStart}
        ondragover={handleDragOver}
        ondrop={handleDrop}
        ondragend={handleDragEnd}
        ondragleave={handleDragLeave}
        dropIndicator={dropTarget?.id === tab.id ? dropTarget.side : null}
        onkeydown={handleKeyDown}
      />
    {/each}
  </div>

  <!-- The "+" button lives OUTSIDE role="tablist" — a tablist is only allowed to contain
       role="tab" children (axe `aria-required-children`). Keeping it adjacent to the
       scroll container preserves the visual placement at the end of the tab strip. -->
  <button
    bind:this={openBtnEl}
    onclick={() => {
      recentFiles = loadRecentFilesCached();
      showRecent = !showRecent;
    }}
    data-testid="open-file-btn"
    title="Open file"
    style="background: none; border: none; border-radius: var(--tandem-r-2); cursor: pointer; font-size: 16px; line-height: 1; color: var(--tandem-fg-subtle); padding: 0 8px; margin-left: 4px; flex-shrink: 0;"
    onmouseenter={(e) => {
      (e.currentTarget as HTMLButtonElement).style.color = "var(--tandem-accent)";
      (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--tandem-accent)";
    }}
    onmouseleave={(e) => {
      (e.currentTarget as HTMLButtonElement).style.color = "var(--tandem-fg-muted)";
      (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--tandem-border-strong)";
    }}
  >
    +
  </button>

  {#if canScrollRight}
    <button
      data-testid="tab-scroll-right"
      onclick={scrollRight}
      style="display: flex; align-items: center; justify-content: center; width: 28px; min-width: 28px; background: linear-gradient(to left, var(--tandem-surface-muted) 70%, transparent); border: none; cursor: pointer; font-size: 12px; color: var(--tandem-fg-muted); padding: 0; z-index: 1;"
      title="Scroll tabs right"
    >
      ▶
    </button>
  {/if}

  {#if showRecent}
    <NewTabMenu
      {recentFiles}
      anchorEl={openBtnEl}
      onOpen={async (filePath) => {
        showRecent = false;
        try {
          const res = await fetch(`${API_BASE}${API_OPEN}`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ filePath }),
          });
          if (res.ok) {
            saveRecentFiles(addRecentFile(loadRecentFilesCached(), filePath));
          } else {
            const err = await res.text();
            console.warn("[tandem] failed to open recent file:", err);
          }
        } catch (err) {
          console.warn("[tandem] failed to open recent file:", err);
        }
      }}
      onNewScratchpad={() => {
        showRecent = false;
        void createScratchpad();
      }}
      onBrowse={() => {
        showRecent = false;
        showDialog = true;
      }}
      onClose={() => (showRecent = false)}
    />
  {/if}

  {#if showDialog}
    <FileOpenDialog onClose={() => (showDialog = false)} />
  {/if}
</div>

<style>
  :global(.tab-scroll-hide) {
    scrollbar-width: none;
    -ms-overflow-style: none;
  }
  :global(.tab-scroll-hide::-webkit-scrollbar) {
    display: none;
  }
</style>

// src/client/tabs/DocumentTabs.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import { FileOpenDialog } from "../components/FileOpenDialog";
import { useTabDirty } from "../hooks/useTabDirty";
import type { OpenTab } from "../types";

interface DocumentTabsProps {
  tabs: OpenTab[];
  activeTabId: string | null;
  onTabSwitch: (tabId: string) => void;
  onTabClose: (tabId: string) => void;
  reorder?: (fromId: string, toId: string, side?: "left" | "right") => void;
  reduceMotion?: boolean;
}

const FORMAT_ICONS: Record<string, string> = {
  md: "M",
  txt: "T",
  html: "H",
  docx: "W",
};

interface TabItemProps {
  tab: OpenTab;
  isActive: boolean;
  onSwitch: (id: string) => void;
  onClose: (id: string) => void;
  draggable: boolean;
  onDragStart: (e: React.DragEvent, id: string) => void;
  onDragOver: (e: React.DragEvent, id: string) => void;
  onDrop: (e: React.DragEvent, id: string) => void;
  onDragEnd: () => void;
  onDragLeave: () => void;
  dropIndicator: "left" | "right" | null;
  onKeyDown: (e: React.KeyboardEvent, id: string) => void;
}

/** Extracted so useTabDirty can be called per-tab (hooks can't run in loops). */
function TabItem({
  tab,
  isActive,
  onSwitch,
  onClose,
  draggable,
  onDragStart,
  onDragOver,
  onDrop,
  onDragEnd,
  onDragLeave,
  dropIndicator,
  onKeyDown,
}: TabItemProps) {
  const isDirty = useTabDirty(tab);

  return (
    <div
      data-testid={`tab-${tab.id}`}
      data-active={isActive}
      onClick={() => onSwitch(tab.id)}
      draggable={draggable}
      tabIndex={0}
      onDragStart={(e) => onDragStart(e, tab.id)}
      onDragOver={(e) => onDragOver(e, tab.id)}
      onDrop={(e) => onDrop(e, tab.id)}
      onDragEnd={onDragEnd}
      onDragLeave={onDragLeave}
      onKeyDown={(e) => onKeyDown(e, tab.id)}
      style={{
        display: "flex",
        alignItems: "center",
        gap: "6px",
        padding: "4px 12px",
        fontSize: "13px",
        cursor: "pointer",
        background: isActive ? "var(--tandem-surface)" : "transparent",
        color: isActive ? "var(--tandem-fg)" : "var(--tandem-fg-muted)",
        borderTop: isActive ? "2px solid var(--tandem-accent)" : "2px solid transparent",
        borderBottom: isActive ? "1px solid var(--tandem-surface)" : "1px solid transparent",
        borderLeft:
          dropIndicator === "left" ? "2px solid var(--tandem-accent)" : "2px solid transparent",
        borderRight:
          dropIndicator === "right" ? "2px solid var(--tandem-accent)" : "2px solid transparent",
        marginBottom: "-1px",
        userSelect: "none",
        whiteSpace: "nowrap",
        transition: "background 0.15s, color 0.15s",
        flexShrink: 0,
      }}
    >
      {isDirty && (
        <span
          data-testid={`unsaved-indicator-${tab.id}`}
          style={{ color: "#f59e0b", fontSize: "10px" }}
        >
          ●
        </span>
      )}
      <span
        style={{
          fontSize: "10px",
          fontWeight: 700,
          color: isActive ? "var(--tandem-accent)" : "var(--tandem-fg-subtle)",
          width: "14px",
          textAlign: "center",
        }}
      >
        {FORMAT_ICONS[tab.format] || "?"}
      </span>
      <span
        data-testid={`tab-name-${tab.id}`}
        title={tab.filePath}
        style={{
          fontWeight: isActive ? 500 : 400,
          maxWidth: "160px",
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
        }}
      >
        {tab.fileName}
      </span>
      {tab.readOnly && (
        <span
          style={{
            fontSize: "9px",
            color: "var(--tandem-warning)",
            background: "var(--tandem-warning-bg)",
            padding: "0 3px",
            borderRadius: "2px",
          }}
        >
          RO
        </span>
      )}
      <button
        onClick={(e) => {
          e.stopPropagation();
          onClose(tab.id);
        }}
        onDragOver={(e) => {
          e.stopPropagation();
          e.preventDefault();
        }}
        onDrop={(e) => {
          e.stopPropagation();
          e.preventDefault();
        }}
        style={{
          background: "none",
          border: "none",
          cursor: "pointer",
          fontSize: "14px",
          lineHeight: 1,
          color: "var(--tandem-fg-subtle)",
          padding: "0 2px",
          borderRadius: "2px",
        }}
        onMouseEnter={(e) => (e.currentTarget.style.color = "var(--tandem-error)")}
        onMouseLeave={(e) => (e.currentTarget.style.color = "var(--tandem-fg-subtle)")}
        title="Close document"
      >
        ×
      </button>
    </div>
  );
}

/** Scrollbar-hiding style tag — injected once. */
const SCROLLBAR_HIDE_CLASS = "tandem-tab-scroll-hide";
function ScrollbarHideStyle() {
  return (
    <style>{`
      .${SCROLLBAR_HIDE_CLASS} {
        scrollbar-width: none;
        -ms-overflow-style: none;
      }
      .${SCROLLBAR_HIDE_CLASS}::-webkit-scrollbar {
        display: none;
      }
    `}</style>
  );
}

const ARROW_BTN_STYLE: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  width: "28px",
  minWidth: "28px",
  background: "linear-gradient(to right, var(--tandem-surface-muted) 70%, transparent)",
  border: "none",
  cursor: "pointer",
  fontSize: "12px",
  color: "var(--tandem-fg-muted)",
  padding: 0,
  zIndex: 1,
};

const ARROW_BTN_RIGHT_STYLE: React.CSSProperties = {
  ...ARROW_BTN_STYLE,
  background: "linear-gradient(to left, var(--tandem-surface-muted) 70%, transparent)",
};

export function DocumentTabs({
  tabs,
  activeTabId,
  onTabSwitch,
  onTabClose,
  reorder,
  reduceMotion,
}: DocumentTabsProps) {
  const scrollBehavior: ScrollBehavior = reduceMotion ? "auto" : "smooth";
  const [showDialog, setShowDialog] = useState(false);
  /** Prevent double-click on close button from firing multiple close requests. */
  const closingIdsRef = useRef<Set<string>>(new Set());
  // Clean up stale entries when tabs change (closed tab removed from DOM)
  useEffect(() => {
    const currentIds = new Set(tabs.map((t) => t.id));
    for (const id of closingIdsRef.current) {
      if (!currentIds.has(id)) closingIdsRef.current.delete(id);
    }
  }, [tabs]);
  const guardedClose = useCallback(
    (tabId: string) => {
      if (closingIdsRef.current.has(tabId)) return;
      closingIdsRef.current.add(tabId);
      onTabClose(tabId);
    },
    [onTabClose],
  );
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const [dropTarget, setDropTarget] = useState<{
    id: string;
    side: "left" | "right";
  } | null>(null);

  function clearDragState(): void {
    setDraggedId(null);
    setDropTarget(null);
  }

  // Overflow detection
  const updateScrollState = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    setCanScrollLeft(el.scrollLeft > 0);
    setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 1);
  }, []);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    updateScrollState();
    el.addEventListener("scroll", updateScrollState, { passive: true });
    const observer = new ResizeObserver(updateScrollState);
    observer.observe(el);
    return () => {
      el.removeEventListener("scroll", updateScrollState);
      observer.disconnect();
    };
  }, [updateScrollState]);

  // Re-check overflow when tabs change
  useEffect(() => {
    updateScrollState();
  }, [tabs.length, updateScrollState]);

  // Auto-scroll active tab into view
  useEffect(() => {
    if (!activeTabId || !scrollRef.current) return;
    const el = scrollRef.current.querySelector(`[data-testid="tab-${activeTabId}"]`);
    if (el) {
      (el as HTMLElement).scrollIntoView({
        inline: "nearest",
        block: "nearest",
        behavior: scrollBehavior,
      });
    }
  }, [activeTabId, scrollBehavior]);

  // Clear drag state when tab list changes mid-drag
  useEffect(() => {
    clearDragState();
  }, [tabs.length]);

  // DnD handlers
  const handleDragStart = useCallback((e: React.DragEvent, id: string) => {
    setDraggedId(id);
    e.dataTransfer.setData("text/plain", id);
    e.dataTransfer.effectAllowed = "move";
  }, []);

  const handleDragOver = useCallback(
    (e: React.DragEvent, id: string) => {
      e.preventDefault();
      if (!draggedId || draggedId === id) {
        setDropTarget(null);
        return;
      }
      const rect = e.currentTarget.getBoundingClientRect();
      const midX = rect.left + rect.width / 2;
      const side = e.clientX < midX ? "left" : "right";
      setDropTarget({ id, side });
    },
    [draggedId],
  );

  const handleDrop = useCallback(
    (e: React.DragEvent, targetId: string) => {
      e.preventDefault();
      const fromId = e.dataTransfer.getData("text/plain");
      if (fromId && fromId !== targetId && reorder) {
        // Use the drop indicator side to determine insert position
        const rect = e.currentTarget.getBoundingClientRect();
        const midX = rect.left + rect.width / 2;
        const side = e.clientX < midX ? "left" : "right";
        reorder(fromId, targetId, side);
      }
      clearDragState();
    },
    [reorder],
  );

  const handleDragEnd = useCallback(() => {
    clearDragState();
  }, []);

  const handleDragLeave = useCallback(() => {
    setDropTarget(null);
  }, []);

  // Keyboard reordering (Alt+Arrow swaps with neighbor)
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent, id: string) => {
      if (!e.altKey || !reorder) return;
      if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") return;
      e.preventDefault();

      const idx = tabs.findIndex((t) => t.id === id);
      if (idx === -1) return;

      if (e.key === "ArrowLeft" && idx > 0) {
        // Place this tab before the one to its left
        reorder(id, tabs[idx - 1].id);
      } else if (e.key === "ArrowRight" && idx < tabs.length - 1) {
        // Place the neighbor before this tab (effectively swapping right)
        reorder(tabs[idx + 1].id, id);
      }
    },
    [tabs, reorder],
  );

  const scrollLeft = useCallback(() => {
    scrollRef.current?.scrollBy({ left: -150, behavior: scrollBehavior });
  }, [scrollBehavior]);

  const scrollRight = useCallback(() => {
    scrollRef.current?.scrollBy({ left: 150, behavior: scrollBehavior });
  }, [scrollBehavior]);

  const singleTab = tabs.length <= 1;

  return (
    <div
      style={{
        position: "relative",
        display: "flex",
        alignItems: "center",
        background: "var(--tandem-surface-muted)",
        borderBottom: "1px solid var(--tandem-border)",
        minHeight: "32px",
      }}
    >
      <ScrollbarHideStyle />
      {canScrollLeft && (
        <button
          data-testid="tab-scroll-left"
          onClick={scrollLeft}
          style={ARROW_BTN_STYLE}
          title="Scroll tabs left"
        >
          ◀
        </button>
      )}
      <div
        ref={scrollRef}
        data-testid="tab-scroll-container"
        className={SCROLLBAR_HIDE_CLASS}
        style={{
          display: "flex",
          alignItems: "center",
          gap: "1px",
          flex: 1,
          overflowX: "auto",
          overflowY: "hidden",
          padding: "0 4px",
        }}
      >
        {tabs.map((tab) => (
          <TabItem
            key={tab.id}
            tab={tab}
            isActive={tab.id === activeTabId}
            onSwitch={onTabSwitch}
            onClose={guardedClose}
            draggable={!singleTab}
            onDragStart={handleDragStart}
            onDragOver={handleDragOver}
            onDrop={handleDrop}
            onDragEnd={handleDragEnd}
            onDragLeave={handleDragLeave}
            dropIndicator={dropTarget?.id === tab.id ? dropTarget.side : null}
            onKeyDown={handleKeyDown}
          />
        ))}
      </div>
      {canScrollRight && (
        <button
          data-testid="tab-scroll-right"
          onClick={scrollRight}
          style={ARROW_BTN_RIGHT_STYLE}
          title="Scroll tabs right"
        >
          ▶
        </button>
      )}
      <button
        onClick={() => setShowDialog(true)}
        data-testid="open-file-btn"
        title="Open file"
        style={{
          background: "none",
          border: "1px solid var(--tandem-border-strong)",
          borderRadius: "4px",
          cursor: "pointer",
          fontSize: "16px",
          lineHeight: 1,
          color: "var(--tandem-fg-muted)",
          padding: "2px 8px",
          marginLeft: "4px",
          marginRight: "8px",
          flexShrink: 0,
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.color = "var(--tandem-accent)";
          e.currentTarget.style.borderColor = "var(--tandem-accent)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.color = "var(--tandem-fg-muted)";
          e.currentTarget.style.borderColor = "var(--tandem-border-strong)";
        }}
      >
        +
      </button>
      {showDialog && <FileOpenDialog onClose={() => setShowDialog(false)} />}
    </div>
  );
}
