// src/client/editor/Editor.svelte
<script lang="ts">
import { HocuspocusProvider } from "@hocuspocus/provider";
import { Editor as TiptapEditor } from "@tiptap/core";
import Collaboration from "@tiptap/extension-collaboration";
import CollaborationCursor from "@tiptap/extension-collaboration-cursor";
import Highlight from "@tiptap/extension-highlight";
import Link from "@tiptap/extension-link";
import Placeholder from "@tiptap/extension-placeholder";
import Table from "@tiptap/extension-table";
import TableCell from "@tiptap/extension-table-cell";
import TableHeader from "@tiptap/extension-table-header";
import TableRow from "@tiptap/extension-table-row";
import StarterKit from "@tiptap/starter-kit";
import { untrack } from "svelte";
import * as Y from "yjs";
import { readStoredName, subscribeToUserName } from "../hooks/useUserName";
import { AnnotationExtension } from "./extensions/annotation";
import { AuthorshipExtension } from "./extensions/authorship";
import { AwarenessExtension } from "./extensions/awareness";
import { FindReplaceExtension } from "./extensions/find-replace";
import { MarkdownHtmlExtension } from "./extensions/markdown-html";
import { SlashCommandExtension } from "./extensions/slash-command";
import "./editor.css";

interface Props {
  ydoc: Y.Doc;
  provider: HocuspocusProvider;
  readOnly: boolean;
  activeAnnotationId?: string | null;
  onEditorReady?: (editor: TiptapEditor | null) => void;
  onAnnotationClick?: (annotationId: string) => void;
  onSlashCommandMenuChange?: (open: boolean) => void;
}

const {
  ydoc,
  provider,
  readOnly,
  activeAnnotationId,
  onEditorReady,
  onAnnotationClick,
  onSlashCommandMenuChange,
}: Props = $props();

let editor = $state<TiptapEditor | null>(null);
let editorRoot: HTMLDivElement | null = null;

// -------------------------------------------------------------------------
// Editor lifecycle: re-create when (ydoc, provider) identity changes.
//
// Pattern matches CLAUDE.md gotcha "Y.XmlText must be attached before
// populating": Tiptap creates its own Y.XmlFragment binding via the
// Collaboration extension on the supplied ydoc. We must destroy any prior
// editor BEFORE creating the new one (avoid duplicate event subscriptions
// and torn observers). Cleanup runs before the effect re-runs.
// -------------------------------------------------------------------------
$effect(() => {
  // Track identity of ydoc + provider so this effect re-runs on swap.
  void ydoc;
  void provider;

  if (!editorRoot) return;

  const next = new TiptapEditor({
    element: editorRoot,
    extensions: [
      StarterKit.configure({ history: false }), // Yjs handles undo/redo
      Highlight.configure({ multicolor: true }),
      Link.configure({
        openOnClick: false,
        HTMLAttributes: { rel: "noopener noreferrer", target: "_blank" },
      }),
      Placeholder.configure({
        placeholder: "Open a document with Claude to get started...",
      }),
      Table.configure({ resizable: true }),
      TableRow,
      TableCell,
      TableHeader,
      MarkdownHtmlExtension,
      Collaboration.configure({ document: ydoc }),
      CollaborationCursor.configure({
        provider,
        user: {
          name: readStoredName(),
          color: "var(--tandem-warning)",
        },
      }),
      AnnotationExtension.configure({ ydoc }),
      AuthorshipExtension.configure({ ydoc }),
      AwarenessExtension.configure({ ydoc }),
      SlashCommandExtension.configure({ onOpenChange: onSlashCommandMenuChange }),
      FindReplaceExtension,
    ],
    editorProps: {
      attributes: {
        class: "tandem-editor",
        style:
          "outline: none; min-height: 500px; font-size: var(--tandem-editor-font-size, 16px); line-height: 1.6;",
      },
    },
    editable: untrack(() => !readOnly),
  });

  editor = next;
  untrack(() => onEditorReady?.(next));

  return () => {
    untrack(() => onEditorReady?.(null));
    next.destroy();
    if (editor === next) editor = null;
  };
});

// -- readOnly toggling without recreating the editor -----------------------
$effect(() => {
  const ed = editor;
  if (!ed) return;
  ed.setEditable(!readOnly);
});

// -- Keep CollaborationCursor name synced with stored display name --------
$effect(() => {
  const ed = editor;
  if (!ed) return;
  return subscribeToUserName((name) => ed.commands.updateUser({ name }));
});

// -- Apply active annotation highlight class -------------------------------
$effect(() => {
  const ed = editor;
  if (!ed) return;
  const container = ed.view.dom;

  container.querySelectorAll(".tandem-annotation-active").forEach((el) => {
    el.classList.remove("tandem-annotation-active");
  });

  if (activeAnnotationId) {
    container
      .querySelectorAll(`[data-annotation-id="${CSS.escape(activeAnnotationId)}"]`)
      .forEach((el) => {
        el.classList.add("tandem-annotation-active");
      });
  }
});

function handleEditorClick(e: MouseEvent) {
  const target = (e.target as HTMLElement).closest("[data-annotation-id]");
  if (!target) return;
  const annotationId = target.getAttribute("data-annotation-id");
  if (annotationId && onAnnotationClick) {
    onAnnotationClick(annotationId);
  }
}
</script>

<div bind:this={editorRoot} onclick={handleEditorClick} role="presentation"></div>

<style>
  /* Apply editor font to the Tiptap content DOM (inside Tiptap's own element tree). */
  :global(.tandem-editor) {
    font-family: var(--tandem-editor-font-family);
  }
</style>

// src/client/editor/Editor.tsx
import { HocuspocusProvider } from "@hocuspocus/provider";
import Collaboration from "@tiptap/extension-collaboration";
import CollaborationCursor from "@tiptap/extension-collaboration-cursor";
import Highlight from "@tiptap/extension-highlight";
import Link from "@tiptap/extension-link";
import Placeholder from "@tiptap/extension-placeholder";
import Table from "@tiptap/extension-table";
import TableCell from "@tiptap/extension-table-cell";
import TableHeader from "@tiptap/extension-table-header";
import TableRow from "@tiptap/extension-table-row";
import type { Editor as TiptapEditor } from "@tiptap/react";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import React, { useCallback, useEffect } from "react";
import * as Y from "yjs";
import { readStoredName, subscribeToUserName } from "../hooks/useUserName";
import { AnnotationExtension } from "./extensions/annotation";
import { AuthorshipExtension } from "./extensions/authorship";
import { AwarenessExtension } from "./extensions/awareness";

interface EditorProps {
  ydoc: Y.Doc;
  provider: HocuspocusProvider;
  readOnly: boolean;
  reviewMode?: boolean;
  activeAnnotationId?: string | null;
  onEditorReady?: (editor: TiptapEditor | null) => void;
  onAnnotationClick?: (annotationId: string) => void;
}

export function Editor({
  ydoc,
  provider,
  readOnly,
  reviewMode,
  activeAnnotationId,
  onEditorReady,
  onAnnotationClick,
}: EditorProps) {
  const editor = useEditor(
    {
      extensions: [
        StarterKit.configure({
          history: false, // Yjs handles undo/redo
        }),
        Highlight.configure({ multicolor: true }),
        Link.configure({
          openOnClick: false,
          HTMLAttributes: { rel: "noopener noreferrer", target: "_blank" },
        }),
        Placeholder.configure({
          placeholder: "Open a document with Claude to get started...",
        }),
        Table.configure({ resizable: true }),
        TableRow,
        TableCell,
        TableHeader,
        Collaboration.configure({
          document: ydoc,
        }),
        CollaborationCursor.configure({
          provider: provider,
          user: {
            name: readStoredName(),
            color: "var(--tandem-warning)",
          },
        }),
        AnnotationExtension.configure({ ydoc }),
        AuthorshipExtension.configure({ ydoc }),
        AwarenessExtension.configure({ ydoc }),
      ],
      editorProps: {
        attributes: {
          class: "tandem-editor",
          style:
            "outline: none; min-height: 500px; font-size: var(--tandem-editor-font-size, 16px); line-height: 1.6;",
        },
      },
    },
    [ydoc, provider],
  ); // Re-create editor if ydoc or provider change

  // Toggle editable mode without recreating the editor (preserves HocuspocusProvider)
  useEffect(() => {
    if (editor) {
      editor.setEditable(!readOnly);
    }
  }, [editor, readOnly]);

  // Keep the CollaborationCursor label in sync with the display name. The
  // cursor user is captured at editor creation, so a later name edit from
  // StatusBar or Settings won't propagate without this subscription.
  useEffect(() => {
    if (!editor) return;
    return subscribeToUserName((name) => editor.commands.updateUser({ name }));
  }, [editor]);

  useEffect(() => {
    onEditorReady?.(editor);
    return () => onEditorReady?.(null);
  }, [editor, onEditorReady]);

  // Apply active annotation highlight class based on activeAnnotationId
  useEffect(() => {
    if (!editor) return;
    const container = editor.view.dom;

    container.querySelectorAll(".tandem-annotation-active").forEach((el) => {
      el.classList.remove("tandem-annotation-active");
    });

    if (activeAnnotationId && reviewMode) {
      container
        .querySelectorAll(`[data-annotation-id="${CSS.escape(activeAnnotationId)}"]`)
        .forEach((el) => {
          el.classList.add("tandem-annotation-active");
        });
    }
  }, [editor, activeAnnotationId, reviewMode]);

  const handleEditorClick = useCallback(
    (e: React.MouseEvent) => {
      const target = (e.target as HTMLElement).closest("[data-annotation-id]");
      if (!target) return;
      const annotationId = target.getAttribute("data-annotation-id");
      if (annotationId && onAnnotationClick) {
        onAnnotationClick(annotationId);
      }
    },
    [onAnnotationClick],
  );

  const containerClass = reviewMode ? "tandem-review-dimmed" : "";

  return (
    <div className={containerClass} onClick={handleEditorClick}>
      <EditorContent editor={editor} />
      <style>{`
        .tandem-editor h1 { font-size: 2em; font-weight: 700; margin: 0.67em 0; }
        .tandem-editor h2 { font-size: 1.5em; font-weight: 600; margin: 0.75em 0; }
        .tandem-editor h3 { font-size: 1.17em; font-weight: 600; margin: 0.83em 0; }
        .tandem-editor p { margin: 0.5em 0; }
        .tandem-editor ul, .tandem-editor ol { padding-left: 1.5em; }
        .tandem-editor table { border-collapse: collapse; width: 100%; margin: 1em 0; }
        .tandem-editor td, .tandem-editor th { border: 1px solid var(--tandem-border); padding: 8px; }
        .tandem-editor th { background: var(--tandem-surface-muted); font-weight: 600; }
        .tandem-editor blockquote {
          border-left: 3px solid var(--tandem-border-strong);
          margin: 0.5em 0;
          padding-left: 1em;
          color: var(--tandem-fg-muted);
        }
        .collaboration-cursor__caret {
          position: relative;
          border-left: 2px solid;
          border-right: none;
          margin-left: -1px;
        }
        .collaboration-cursor__label {
          position: absolute;
          top: -1.4em;
          left: -1px;
          font-size: 12px;
          white-space: nowrap;
          padding: 0 4px;
          border-radius: 3px 3px 3px 0;
          color: var(--tandem-accent-fg);
        }
        .ProseMirror-focused { outline: none; }
        .ProseMirror p.is-empty::before {
          content: attr(data-placeholder);
          color: var(--tandem-fg-subtle);
          pointer-events: none;
          float: left;
          height: 0;
        }

        /* Annotation decorations */
        .tandem-highlight { cursor: pointer; }
        .tandem-highlight:hover { filter: brightness(0.95); }
        .tandem-comment { cursor: pointer; }
        .tandem-comment:hover { border-bottom-style: solid; }
        .tandem-suggestion { cursor: pointer; }

        /* Review mode dimming — grays out text, keeps annotated spans readable */
        .tandem-review-dimmed .ProseMirror {
          color: var(--tandem-fg-subtle);
          transition: color 0.2s;
        }
        .tandem-review-dimmed .tandem-highlight,
        .tandem-review-dimmed .tandem-comment,
        .tandem-review-dimmed .tandem-suggestion {
          color: var(--tandem-fg);
        }
        .tandem-review-dimmed .tandem-annotation-active {
          outline: 2px solid var(--tandem-accent);
          outline-offset: 1px;
          border-radius: 2px;
        }

        /* Authorship decorations — user=blue, claude=orange */
        .tandem-authorship { transition: color 0.2s; }
        .tandem-authorship--user { color: var(--tandem-author-user); }
        .tandem-authorship--claude { color: var(--tandem-author-claude); }

        /* Claude focus paragraph */
        .tandem-claude-focus {
          position: relative;
        }
        .tandem-claude-focus::before {
          content: '';
          position: absolute;
          left: -24px;
          top: 0;
          bottom: 0;
          width: 3px;
          background: var(--tandem-accent);
          border-radius: 2px;
          animation: tandem-gutter-pulse 2s ease-in-out infinite;
        }
        @keyframes tandem-gutter-pulse {
          0%, 100% { opacity: 0.4; }
          50% { opacity: 1; }
        }

        /* Claude character-level cursor */
        .tandem-claude-cursor {
          position: relative;
          display: inline;
          border-left: 2px solid var(--tandem-author-claude);
          margin-left: -1px;
          z-index: 10;
          animation: tandem-claude-blink 1.2s step-end infinite;
        }
        .tandem-claude-cursor-idle {
          opacity: 0.3;
          animation: none;
        }
        .tandem-claude-cursor-label {
          position: absolute;
          top: -1.4em;
          left: -1px;
          font-size: 11px;
          font-weight: 500;
          white-space: nowrap;
          padding: 0 4px;
          border-radius: 3px 3px 3px 0;
          background: var(--tandem-author-claude);
          color: var(--tandem-accent-fg);
          pointer-events: none;
          z-index: 11;
        }
        @keyframes tandem-claude-blink {
          0%, 100% { opacity: 1; }
          50% { opacity: 0; }
        }
      `}</style>
    </div>
  );
}
