// src/client/editor/toolbar/ModeToggle.svelte
<script lang="ts">
import type { TandemMode } from "../../../shared/types";

interface Props {
  tandemMode: TandemMode;
  onModeChange: (mode: TandemMode) => void;
}

const { tandemMode, onModeChange }: Props = $props();
</script>

<div
  data-testid="mode-toggle"
  role="group"
  aria-label="AI collaboration mode"
  style="display: inline-flex; background: var(--tandem-surface-sunk); border: 1px solid var(--tandem-border); border-radius: var(--tandem-r-2); padding: 2px; gap: 2px;"
>
  <button
    data-testid="mode-solo-btn"
    title="Write undisturbed — your AI only responds when you message"
    aria-pressed={tandemMode === "solo"}
    onclick={() => onModeChange("solo")}
    style="height: 24px; padding: 0 10px; font-size: 12px; border: none; border-radius: var(--tandem-r-1); cursor: pointer;
      background: {tandemMode === 'solo' ? 'var(--tandem-surface)' : 'transparent'};
      color: {tandemMode === 'solo' ? 'var(--tandem-fg)' : 'var(--tandem-fg-muted)'};
      font-weight: 500;
      display: flex; align-items: center; gap: 5px;"
  >
    {#if tandemMode === "solo"}
      <span
        style="width: 6px; height: 6px; border-radius: var(--tandem-r-circle); background: var(--tandem-fg-subtle); display: inline-block;"
      ></span>
    {/if}
    Solo
  </button>
  <button
    data-testid="mode-tandem-btn"
    title="Full collaboration — your AI reacts to selections and document changes"
    aria-pressed={tandemMode === "tandem"}
    onclick={() => onModeChange("tandem")}
    style="height: 24px; padding: 0 10px; font-size: 12px; border: none; border-radius: var(--tandem-r-1); cursor: pointer;
      background: {tandemMode === 'tandem' ? 'var(--tandem-surface)' : 'transparent'};
      color: {tandemMode === 'tandem' ? 'var(--tandem-fg)' : 'var(--tandem-fg-muted)'};
      font-weight: 500;
      display: flex; align-items: center; gap: 5px;"
  >
    {#if tandemMode === "tandem"}
      <span
        style="width: 6px; height: 6px; border-radius: var(--tandem-r-circle); background: var(--tandem-success); display: inline-block;"
      ></span>
    {/if}
    Tandem
  </button>
</div>

<style>
  @media (forced-colors: active) {
    button[aria-pressed="true"] {
      outline: 2px solid ButtonText;
    }
  }
</style>

// src/client/editor/toolbar/ModeToggle.tsx
import type { TandemMode } from "../../../shared/types";

interface ModeToggleProps {
  tandemMode: TandemMode;
  onModeChange: (mode: TandemMode) => void;
}

export function ModeToggle({ tandemMode, onModeChange }: ModeToggleProps) {
  return (
    <div
      data-testid="mode-toggle"
      role="group"
      aria-label="Claude collaboration mode"
      style={{
        display: "flex",
        border: "1px solid var(--tandem-border-strong)",
        borderRadius: "4px",
        overflow: "hidden",
      }}
    >
      <button
        data-testid="mode-solo-btn"
        title="Write undisturbed — Claude only responds when you message"
        aria-pressed={tandemMode === "solo"}
        onClick={() => onModeChange("solo")}
        style={{
          padding: "3px 10px",
          fontSize: "12px",
          border: "none",
          cursor: "pointer",
          background: tandemMode === "solo" ? "var(--tandem-accent)" : "transparent",
          color: tandemMode === "solo" ? "var(--tandem-accent-fg)" : "var(--tandem-fg-muted)",
          fontWeight: tandemMode === "solo" ? 600 : 400,
          borderRight: "1px solid var(--tandem-border-strong)",
          display: "flex",
          alignItems: "center",
          gap: "5px",
        }}
      >
        {tandemMode === "solo" && (
          <span
            style={{
              width: "6px",
              height: "6px",
              borderRadius: "50%",
              background: "var(--tandem-fg-subtle)",
              display: "inline-block",
            }}
          />
        )}
        Solo
      </button>
      <button
        data-testid="mode-tandem-btn"
        title="Full collaboration — Claude reacts to selections and document changes"
        aria-pressed={tandemMode === "tandem"}
        onClick={() => onModeChange("tandem")}
        style={{
          padding: "3px 10px",
          fontSize: "12px",
          border: "none",
          cursor: "pointer",
          background: tandemMode === "tandem" ? "var(--tandem-accent)" : "transparent",
          color: tandemMode === "tandem" ? "var(--tandem-accent-fg)" : "var(--tandem-fg-muted)",
          fontWeight: tandemMode === "tandem" ? 600 : 400,
          display: "flex",
          alignItems: "center",
          gap: "5px",
        }}
      >
        {tandemMode === "tandem" && (
          <span
            style={{
              width: "6px",
              height: "6px",
              borderRadius: "50%",
              background: "var(--tandem-success)",
              display: "inline-block",
            }}
          />
        )}
        Tandem
      </button>
    </div>
  );
}
