// src/client/editor/toolbar/ToolbarButton.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
  /** When provided as a snippet, the snippet is rendered inside the button.
   * Otherwise `label` is rendered as a plain string. */
  label?: string;
  children?: Snippet;
  ariaLabel?: string;
  testId?: string;
  shortcut?: string;
  disabled?: boolean;
  disabledTitle?: string;
  active?: boolean;
  onMouseDown?: (e: MouseEvent) => void;
  onClick?: () => void;
  style?: string;
}

const {
  label,
  children,
  ariaLabel,
  testId,
  shortcut,
  disabled = false,
  disabledTitle,
  active = false,
  onMouseDown,
  onClick,
  style = "",
}: Props = $props();

const computed = $derived.by(() => {
  let border = "1px solid transparent";
  let background = "transparent";
  let color = "var(--tandem-fg-muted)";

  if (disabled) {
    background = "transparent";
    color = "var(--tandem-fg-subtle)";
  } else if (active) {
    background = "var(--tandem-accent-bg)";
    border = "1px solid var(--tandem-accent-border)";
    color = "var(--tandem-accent-fg-strong)";
  }
  return { border, background, color };
});

const ariaLabelValue = $derived(ariaLabel ?? (typeof label === "string" ? label : undefined));
const titleText = $derived(ariaLabelValue ?? "");
const titleAttr = $derived(
  disabled && disabledTitle ? disabledTitle : shortcut ? `${titleText} (${shortcut})` : titleText,
);

const baseStyle =
  "height: 28px; padding: 0 8px; font-size: 12px; border-radius: 5px; display: inline-flex; align-items: center; justify-content: center; gap: 5px;";

const fullStyle = $derived(
  `${baseStyle} cursor: ${disabled ? "not-allowed" : "pointer"}; ${style}; border: ${computed.border}; background: ${computed.background}; color: ${computed.color};`,
);
</script>

<button
  type="button"
  data-testid={testId}
  {disabled}
  title={titleAttr}
  aria-label={ariaLabelValue}
  onmousedown={onMouseDown}
  onclick={onClick}
  style={fullStyle}
>
  {#if children}{@render children()}{:else}{label}{/if}
</button>

// src/client/editor/toolbar/ToolbarButton.tsx
import React from "react";

type ToolbarButtonProps = (
  | { label: string; ariaLabel?: string; testId?: string }
  | { label: React.ReactNode; ariaLabel: string; testId?: string }
) & {
  shortcut?: string;
  disabled?: boolean;
  disabledTitle?: string;
  active?: boolean;
  onMouseDown?: (e: React.MouseEvent) => void;
  onClick?: () => void;
  style?: React.CSSProperties;
};

export function ToolbarButton({
  label,
  ariaLabel,
  testId,
  shortcut,
  disabled,
  disabledTitle,
  active,
  onMouseDown,
  onClick,
  style,
}: ToolbarButtonProps) {
  let border = "1px solid var(--tandem-border)";
  let background = "var(--tandem-surface)";
  let color = "var(--tandem-fg)";

  if (disabled) {
    background = "var(--tandem-surface-muted)";
    color = "var(--tandem-fg-subtle)";
  } else if (active) {
    border = "1px solid var(--tandem-accent)";
    background = "var(--tandem-accent-bg)";
    color = "var(--tandem-accent)";
  }

  const ariaLabelValue = ariaLabel ?? (typeof label === "string" ? label : undefined);
  const titleText = ariaLabelValue ?? "";

  return (
    <button
      type="button"
      data-testid={testId}
      disabled={disabled}
      title={
        disabled && disabledTitle
          ? disabledTitle
          : shortcut
            ? `${titleText} (${shortcut})`
            : titleText
      }
      aria-label={ariaLabelValue}
      onMouseDown={onMouseDown}
      onClick={onClick}
      style={{
        padding: "4px 10px",
        fontSize: "13px",
        borderRadius: "4px",
        cursor: disabled ? "not-allowed" : "pointer",
        ...style,
        border,
        background,
        color,
      }}
    >
      {label}
    </button>
  );
}
