// src/client/panels/DocumentHealth.svelte
<script lang="ts">
// Placeholder component — no analysis available yet.
</script>

<div style="padding: 8px; color: var(--tandem-fg);">
  <h4 style="font-size: 13px; font-weight: 600;">Document Health</h4>
  <p style="font-size: 12px; color: var(--tandem-fg-subtle);">No analysis available.</p>
</div>

// src/client/panels/DocumentHealth.tsx
import React from "react";

export function DocumentHealth() {
  return (
    <div style={{ padding: "8px" }}>
      <h4 style={{ fontSize: "13px", fontWeight: 600 }}>Document Health</h4>
      <p style={{ fontSize: "12px", color: "var(--tandem-fg-subtle)" }}>No analysis available.</p>
    </div>
  );
}
