// src/client/panels/ReviewSummary.tsx
interface ReviewSummaryProps {
  accepted: number;
  dismissed: number;
  total: number;
  onDismiss: () => void;
}

export function ReviewSummary({ accepted, dismissed, total, onDismiss }: ReviewSummaryProps) {
  const acceptRate = total > 0 ? Math.round((accepted / total) * 100) : 0;

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "rgba(0, 0, 0, 0.4)",
        zIndex: 1000,
      }}
      onClick={onDismiss}
    >
      <div
        style={{
          background: "var(--tandem-surface)",
          borderRadius: "12px",
          padding: "32px 40px",
          maxWidth: "400px",
          boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
          textAlign: "center",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ fontSize: "48px", marginBottom: "8px" }}>
          {acceptRate >= 80 ? "\u2705" : acceptRate >= 50 ? "\uD83D\uDCCB" : "\uD83D\uDD0D"}
        </div>
        <h2
          style={{
            margin: "0 0 8px",
            fontSize: "20px",
            fontWeight: 600,
            color: "var(--tandem-fg)",
          }}
        >
          Review Complete
        </h2>
        <p style={{ margin: "0 0 20px", color: "var(--tandem-fg-muted)", fontSize: "14px" }}>
          All annotations have been resolved.
        </p>
        <div
          style={{ display: "flex", justifyContent: "center", gap: "24px", marginBottom: "20px" }}
        >
          <div>
            <div style={{ fontSize: "28px", fontWeight: 700, color: "var(--tandem-success)" }}>
              {accepted}
            </div>
            <div style={{ fontSize: "12px", color: "var(--tandem-fg-muted)" }}>Accepted</div>
          </div>
          <div style={{ width: "1px", background: "var(--tandem-border)" }} />
          <div>
            <div style={{ fontSize: "28px", fontWeight: 700, color: "var(--tandem-error)" }}>
              {dismissed}
            </div>
            <div style={{ fontSize: "12px", color: "var(--tandem-fg-muted)" }}>Dismissed</div>
          </div>
          <div style={{ width: "1px", background: "var(--tandem-border)" }} />
          <div>
            <div style={{ fontSize: "28px", fontWeight: 700, color: "var(--tandem-accent)" }}>
              {acceptRate}%
            </div>
            <div style={{ fontSize: "12px", color: "var(--tandem-fg-muted)" }}>Accept rate</div>
          </div>
        </div>
        <button
          onClick={onDismiss}
          style={{
            padding: "8px 24px",
            fontSize: "14px",
            fontWeight: 500,
            border: "none",
            borderRadius: "6px",
            background: "var(--tandem-accent)",
            color: "var(--tandem-accent-fg)",
            cursor: "pointer",
          }}
        >
          Done
        </button>
      </div>
    </div>
  );
}

// src/client/panels/ReviewSummary.svelte
<script lang="ts">
  interface Props {
    accepted: number;
    dismissed: number;
    total: number;
    onDismiss: () => void;
  }

  let { accepted, dismissed, total, onDismiss }: Props = $props();

  const acceptRate = $derived(total > 0 ? Math.round((accepted / total) * 100) : 0);
  const emoji = $derived(acceptRate >= 80 ? "✅" : acceptRate >= 50 ? "📋" : "🔍");
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<div
  style="position: fixed; inset: 0; display: flex; align-items: center; justify-content: center; background: rgba(0, 0, 0, 0.4); z-index: 1000;"
  onclick={onDismiss}
>
  <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
  <div
    style="background: var(--tandem-surface); border-radius: 12px; padding: 32px 40px; max-width: 400px; box-shadow: 0 20px 60px rgba(0,0,0,0.2); text-align: center;"
    onclick={(e) => e.stopPropagation()}
  >
    <div style="font-size: 48px; margin-bottom: 8px;">{emoji}</div>
    <h2 style="margin: 0 0 8px; font-size: 20px; font-weight: 600; color: var(--tandem-fg);">
      Review Complete
    </h2>
    <p style="margin: 0 0 20px; color: var(--tandem-fg-muted); font-size: 14px;">
      All annotations have been resolved.
    </p>
    <div style="display: flex; justify-content: center; gap: 24px; margin-bottom: 20px;">
      <div>
        <div style="font-size: 28px; font-weight: 700; color: var(--tandem-success);">{accepted}</div>
        <div style="font-size: 12px; color: var(--tandem-fg-muted);">Accepted</div>
      </div>
      <div style="width: 1px; background: var(--tandem-border);"></div>
      <div>
        <div style="font-size: 28px; font-weight: 700; color: var(--tandem-error);">{dismissed}</div>
        <div style="font-size: 12px; color: var(--tandem-fg-muted);">Dismissed</div>
      </div>
      <div style="width: 1px; background: var(--tandem-border);"></div>
      <div>
        <div style="font-size: 28px; font-weight: 700; color: var(--tandem-accent);">{acceptRate}%</div>
        <div style="font-size: 12px; color: var(--tandem-fg-muted);">Accept rate</div>
      </div>
    </div>
    <button
      onclick={onDismiss}
      style="padding: 8px 24px; font-size: 14px; font-weight: 500; border: none; border-radius: 6px; background: var(--tandem-accent); color: var(--tandem-accent-fg); cursor: pointer;"
    >
      Done
    </button>
  </div>
</div>
