// src/client/panels/SidePanel.svelte
<script lang="ts">
import type { Editor as TiptapEditor } from "@tiptap/core";
import { untrack } from "svelte";
import * as Y from "yjs";
import { Y_MAP_ANNOTATION_REPLIES, Y_MAP_ANNOTATIONS } from "../../shared/constants";
import { sanitizeAnnotation } from "../../shared/sanitize";
import type { Annotation, AnnotationReply, TandemMode } from "../../shared/types";
import { isPendingReviewTarget } from "../../shared/types";
import ApplyChangesButton from "../components/ApplyChangesButton.svelte";
import { warningStateColors } from "../utils/colors";
import { API_BASE } from "../utils/fileUpload";
import AnnotationCard from "./AnnotationCard.svelte";
import BulkActions from "./BulkActions.svelte";
import type { FilterAuthor, FilterStatus, FilterType } from "./FilterBar.svelte";
import FilterBar from "./FilterBar.svelte";
import { useAnnotationReview } from "./useAnnotationReview.svelte";

interface Props {
  annotations: Annotation[];
  editor: TiptapEditor | null;
  ydoc: Y.Doc | null;
  heldCount?: number;
  tandemMode?: TandemMode;
  onModeChange?: (mode: TandemMode) => void;
  activeDocFormat?: string;
  documentId?: string;
  reviewMode: boolean;
  onToggleReviewMode: () => void;
  onExitReviewMode: () => void;
  activeAnnotationId: string | null;
  onActiveAnnotationChange: (id: string | null) => void;
  reduceMotion?: boolean;
}

let {
  annotations,
  editor,
  ydoc,
  heldCount = 0,
  tandemMode: _tandemMode,
  onModeChange,
  activeDocFormat,
  documentId,
  reviewMode,
  onToggleReviewMode,
  onExitReviewMode,
  activeAnnotationId,
  onActiveAnnotationChange,
  reduceMotion,
}: Props = $props();

const scrollBehavior: ScrollBehavior = $derived(reduceMotion ? "auto" : "smooth");

// Filter state
let filterType = $state<FilterType>("all");
let filterAuthor = $state<FilterAuthor>("all");
let filterStatus = $state<FilterStatus>("all");
let bulkConfirm = $state<"accept" | "dismiss" | null>(null);

// Scroll container ref
let scrollContainerEl: HTMLDivElement | undefined = $state();

// Confirm button element (from BulkActions)
let confirmBtnEl: HTMLButtonElement | null = $state(null);

// Focus confirm button when bulk confirmation appears
$effect(() => {
  if (bulkConfirm) confirmBtnEl?.focus();
});

// Reset bulk confirm when filters change
$effect(() => {
  // read filter state to establish reactivity
  void filterType;
  void filterAuthor;
  void filterStatus;
  bulkConfirm = null;
});

// Replies: observe Y.Map(annotationReplies)
let repliesMap = $state(new Map<string, AnnotationReply[]>());

$effect(() => {
  if (!ydoc) {
    repliesMap = new Map();
    return;
  }

  const ymap = ydoc.getMap(Y_MAP_ANNOTATION_REPLIES);

  function rebuild() {
    const grouped = new Map<string, AnnotationReply[]>();
    ymap.forEach((value) => {
      const reply = value as AnnotationReply;
      if (reply && typeof reply === "object" && reply.annotationId) {
        const list = grouped.get(reply.annotationId) ?? [];
        list.push(reply);
        grouped.set(reply.annotationId, list);
      }
    });
    for (const list of grouped.values()) {
      list.sort((a, b) => a.timestamp - b.timestamp);
    }
    repliesMap = grouped;
  }

  rebuild();
  ymap.observe(rebuild);
  return () => ymap.unobserve(rebuild);
});

// Single-pass filtering + categorization
const filteredData = $derived.by(() => {
  const filtered: Annotation[] = [];
  const allPending: Annotation[] = [];

  for (const a of annotations) {
    if (a.status === "pending") allPending.push(a);
    let matchType: boolean;
    if (filterType === "all") matchType = true;
    else if (filterType === "with-replacement") matchType = a.suggestedText !== undefined;
    else matchType = a.type === filterType;
    const matchAuthor = filterAuthor === "all" || a.author === filterAuthor;
    const matchStatus = filterStatus === "all" || a.status === filterStatus;
    if (matchType && matchAuthor && matchStatus) filtered.push(a);
  }

  const pending = filtered.filter((a) => a.status === "pending");
  const reviewPending = filtered.filter(isPendingReviewTarget);
  const resolved = filtered.filter((a) => a.status !== "pending");
  const reviewAllPending = annotations.filter(isPendingReviewTarget);

  return { filtered, pending, reviewPending, resolved, allPending, reviewAllPending };
});

const hasFilters = $derived(
  filterType !== "all" || filterAuthor !== "all" || filterStatus !== "all",
);

// useAnnotationReview hook
const review = useAnnotationReview({
  getYdoc: () => ydoc,
  getEditor: () => editor,
  getAnnotations: () => annotations,
  onActiveAnnotationChange: (id) => onActiveAnnotationChange(id),
  getReviewMode: () => reviewMode,
  onToggleReviewMode: () => onToggleReviewMode(),
  onExitReviewMode: () => onExitReviewMode(),
  getBulkConfirm: () => bulkConfirm,
  setBulkConfirm: (v) => (bulkConfirm = v),
  getScrollBehavior: () => scrollBehavior,
});

// Scroll container reset on filter change
let didMountFilters = false;
$effect(() => {
  // track filter state — these are the ONLY reactive deps for this effect
  void filterType;
  void filterAuthor;
  void filterStatus;

  if (!didMountFilters) {
    didMountFilters = true;
    return;
  }

  // Use untrack so reads of activeAnnotationId and scrollContainerEl don't
  // make this effect re-fire when an annotation is clicked (only filter
  // changes should trigger scroll-reset logic).
  untrack(() => {
    if (activeAnnotationId) {
      const card = document.querySelector(`[data-testid="annotation-card-${activeAnnotationId}"]`);
      if (card) {
        card.scrollIntoView({ block: "center" });
        return;
      }
      console.warn(
        `[tandem] SidePanel: active annotation ${activeAnnotationId} not found on filter change; scrolling to top`,
      );
    }
    scrollContainerEl?.scrollTo({ top: 0 });
  });
});

// Scroll to and flash annotation card when activeAnnotationId changes externally
$effect(() => {
  const aid = activeAnnotationId;
  if (!aid) return;
  const sb = scrollBehavior;

  const timer = setTimeout(() => {
    const card = document.querySelector(`[data-testid="annotation-card-${aid}"]`);
    if (card) {
      card.scrollIntoView({ behavior: sb, block: "nearest" });
      card.classList.add("tandem-annotation-flash");
      const onEnd = () => card.classList.remove("tandem-annotation-flash");
      card.addEventListener("animationend", onEnd, { once: true });
    } else {
      console.warn(
        `[tandem] SidePanel: active annotation ${aid} not found after 50ms delay; scroll-to-card skipped`,
      );
    }
  }, 50);

  return () => clearTimeout(timer);
});

function handleEdit(id: string, newContent: string) {
  if (!ydoc) return;
  const map = ydoc.getMap(Y_MAP_ANNOTATIONS);
  const raw = map.get(id) as Annotation | undefined;
  if (!raw) return;
  const ann = sanitizeAnnotation(raw, (event) => {
    console.warn("[sanitize]", event);
  });

  if (ann.suggestedText !== undefined) {
    try {
      const parsed = JSON.parse(newContent) as { suggestedText: string; content: string };
      map.set(id, {
        ...ann,
        suggestedText: parsed.suggestedText,
        content: parsed.content,
        editedAt: Date.now(),
      });
    } catch {
      console.warn(`[SidePanel] Failed to parse edit payload for annotation ${id}`);
    }
    return;
  }
  map.set(id, { ...ann, content: newContent, editedAt: Date.now() });
}

function handleSendToClaude(annotationId: string): void {
  if (!ydoc) return;
  const map = ydoc.getMap(Y_MAP_ANNOTATIONS);
  const raw = map.get(annotationId) as Annotation | undefined;
  if (!raw) return;
  const ann = sanitizeAnnotation(raw, (event) => {
    console.warn("[sanitize]", event);
  });
  map.set(annotationId, { ...ann, type: "comment" });
}

async function handleRemove(annotationId: string): Promise<void> {
  try {
    const resp = await fetch(`${API_BASE}/remove-annotation`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ annotationId, documentId }),
    });
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({ message: "Unknown error" }));
      console.error("[Tandem] Remove annotation failed:", err);
    }
  } catch (e) {
    console.error("[Tandem] Remove annotation failed:", e);
  }
}

async function handleReply(annotationId: string, text: string): Promise<boolean> {
  try {
    const res = await fetch(`${API_BASE}/annotation-reply`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ annotationId, text, documentId }),
    });
    if (!res.ok) {
      const data = (await res.json().catch(() => ({}))) as Record<string, unknown>;
      console.warn(`[SidePanel] Reply failed (${res.status}): ${data.message ?? "unknown error"}`);
      return false;
    }
    return true;
  } catch (err) {
    console.error("[SidePanel] Reply request failed:", err);
    return false;
  }
}

function handleBulk(status: "accepted" | "dismissed") {
  for (const ann of filteredData.reviewPending) review.resolveAnnotation(ann.id, status);
  bulkConfirm = null;
}
</script>

<div
  bind:this={scrollContainerEl}
  data-testid="annotation-list-scroll-container"
  style="width: 100%; background: var(--tandem-surface-muted); display: flex; flex-direction: column; overflow-y: auto;"
>
  <!-- Held-annotation banner -->
  {#if heldCount > 0}
    <div
      style="padding: 10px 14px; margin: 10px 14px 0; background: {warningStateColors.background}; border: 1px solid {warningStateColors.border}; border-radius: 8px; font-size: 12px; color: {warningStateColors.color}; display: flex; justify-content: space-between; align-items: center; gap: 10px;"
    >
      <span data-testid="held-banner">
        {heldCount} annotation{heldCount !== 1 ? "s" : ""} held
      </span>
      <button
        onclick={() => onModeChange?.("tandem")}
        style="font-size: 11px; padding: 4px 10px; border: 1px solid var(--tandem-author-claude); border-radius: 5px; background: var(--tandem-author-claude); color: white; cursor: pointer; font-weight: 500;"
      >
        Show all
      </button>
    </div>
  {/if}

  <!-- Header -->
  <div style="padding: var(--tandem-space-3) var(--tandem-space-4); border-bottom: 1px solid var(--tandem-border);">
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <h3 style="font-size: 13px; font-weight: 600; margin: 0;">
        Annotations
        {#if filteredData.allPending.length > 0}
          <span
            style="margin-left: 8px; padding: 1px 6px; font-size: 11px; background: var(--tandem-accent); color: var(--tandem-accent-fg); border-radius: 10px;"
          >
            {filteredData.allPending.length}
          </span>
        {/if}
      </h3>
      <span
        aria-live="polite"
        style="position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0);"
      >
        {filteredData.allPending.length} pending annotation{filteredData.allPending.length !== 1
          ? "s"
          : ""}
      </span>
      {#if filteredData.allPending.length > 0}
        <div style="display: flex; flex-direction: column; align-items: flex-end;">
          <button
            data-testid="review-mode-btn"
            onclick={onToggleReviewMode}
            title="Keyboard review mode (Ctrl+Shift+R)"
            aria-pressed={reviewMode}
            style="padding: 4px 10px; font-size: 11px; border: 1px solid {reviewMode
              ? 'var(--tandem-accent)'
              : 'var(--tandem-border-strong)'}; border-radius: 3px; background: {reviewMode
              ? 'var(--tandem-accent-bg)'
              : 'var(--tandem-surface)'}; color: {reviewMode
              ? 'var(--tandem-accent)'
              : 'var(--tandem-fg-muted)'}; cursor: pointer; font-weight: {reviewMode ? 600 : 400};"
          >
            {reviewMode ? "Exit Review" : "Review"}
          </button>
          <div
            data-testid="review-shortcut-hints"
            style="font-size: 10px; color: var(--tandem-fg-subtle); margin-top: 2px;"
          >
            Y / N / ↑↓ / Z
          </div>
        </div>
      {/if}
    </div>
  </div>

  <!-- Review mode indicator -->
  {#if reviewMode && review.getReviewTargets().length > 0}
    <div
      style="padding: var(--tandem-space-2) var(--tandem-space-4); background: var(--tandem-accent-bg); border-bottom: 1px solid var(--tandem-border); font-size: 12px; color: var(--tandem-accent-fg-strong);"
    >
      <div aria-live="polite" style="font-weight: 600; margin-bottom: 2px;">
        Reviewing {review.getReviewIndex() + 1} / {review.getReviewTargets().length}
      </div>
      <div style="color: var(--tandem-accent);">
        Tab: next · Shift+Tab: prev · Y: accept · N: dismiss · Z: undo · E: examine · Esc: exit
      </div>
    </div>
  {/if}

  <!-- Filters -->
  <FilterBar
    {filterType}
    {filterAuthor}
    {filterStatus}
    {hasFilters}
    onSetFilterType={(v) => (filterType = v)}
    onSetFilterAuthor={(v) => (filterAuthor = v)}
    onSetFilterStatus={(v) => (filterStatus = v)}
    onClearFilters={() => {
      filterType = "all";
      filterAuthor = "all";
      filterStatus = "all";
    }}
  />

  <!-- Apply as tracked changes (docx only) -->
  <div style="padding: var(--tandem-space-1) var(--tandem-space-4) 0;">
    <ApplyChangesButton {annotations} {activeDocFormat} {documentId} />
  </div>

  <!-- Bulk actions -->
  <BulkActions
    {bulkConfirm}
    pendingCount={filteredData.reviewPending.length}
    allPendingCount={filteredData.reviewAllPending.length}
    bind:confirmRef={confirmBtnEl}
    onConfirmAccept={() => handleBulk("accepted")}
    onConfirmDismiss={() => handleBulk("dismissed")}
    onCancel={() => (bulkConfirm = null)}
    onRequestAccept={() => (bulkConfirm = "accept")}
    onRequestDismiss={() => (bulkConfirm = "dismiss")}
  />

  <!-- Annotation list -->
  <div style="padding: var(--tandem-space-3); flex: 1;" role="list" aria-label="Annotations">
    {#if filteredData.filtered.length === 0}
      <p role="status" style="font-size: 13px; color: var(--tandem-fg-subtle); margin-top: 8px;">
        {hasFilters
          ? "No annotations match filters."
          : "No annotations yet. Open a document to get started."}
      </p>
    {:else}
      {#each filteredData.pending as ann (ann.id)}
        {@const isTarget = review.getActiveReviewAnn()?.id === ann.id}
        <AnnotationCard
          annotation={ann}
          replies={repliesMap.get(ann.id) ?? []}
          isReviewTarget={isTarget}
          onAccept={ann.author !== "user" ? review.handleAccept : undefined}
          onDismiss={ann.author !== "user" ? review.handleDismiss : undefined}
          onRemove={ann.author === "user" ? handleRemove : undefined}
          onSendToClaude={ann.type === "note" ? handleSendToClaude : undefined}
          onEdit={handleEdit}
          onReply={handleReply}
          onClick={() => review.scrollToAnnotation(ann)}
        />
      {/each}
      {#if filteredData.resolved.length > 0}
        <details style="margin-top: 12px;">
          <summary style="font-size: 12px; color: var(--tandem-fg-subtle); cursor: pointer;">
            {filteredData.resolved.length} resolved
          </summary>
          <div role="list" aria-label="Resolved annotations">
            {#each filteredData.resolved as ann (ann.id)}
              <AnnotationCard
                annotation={ann}
                replies={repliesMap.get(ann.id) ?? []}
                onUndo={review.undoResolveAnnotation}
                undoable={review.getRecentlyResolved().has(ann.id)}
                onClick={() => review.scrollToAnnotation(ann)}
              />
            {/each}
          </div>
        </details>
      {/if}
    {/if}
  </div>
</div>

<style>
  @keyframes tandem-annotation-flash {
    0% {
      background-color: color-mix(in srgb, var(--tandem-accent) 20%, transparent);
    }
    100% {
      background-color: transparent;
    }
  }

  :global(.tandem-annotation-flash) {
    animation: tandem-annotation-flash 0.8s ease-out;
  }

  @media (prefers-reduced-motion: reduce) {
    :global(.tandem-annotation-flash) {
      animation: none;
    }
  }

  :global(body.tandem-reduce-motion .tandem-annotation-flash) {
    animation: none;
  }
</style>

// src/client/panels/SidePanel.tsx
import type { Editor as TiptapEditor } from "@tiptap/react";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import * as Y from "yjs";
import { Y_MAP_ANNOTATIONS } from "../../shared/constants";
import type { Annotation, AnnotationType, TandemMode } from "../../shared/types";
import { ApplyChangesButton } from "../components/ApplyChangesButton";
import { useReviewKeyboard } from "../hooks/useReviewKeyboard";
import { annotationToPmRange } from "../positions";
import { AnnotationCard } from "./AnnotationCard";
import { FilterSelect } from "./FilterSelect";

interface SidePanelProps {
  annotations: Annotation[];
  editor: TiptapEditor | null;
  ydoc: Y.Doc | null;
  heldCount?: number;
  tandemMode?: TandemMode;
  onModeChange?: (mode: TandemMode) => void;
  activeDocFormat?: string;
  documentId?: string;
  reviewMode: boolean;
  onToggleReviewMode: () => void;
  onExitReviewMode: () => void;
  activeAnnotationId: string | null;
  onActiveAnnotationChange: (id: string | null) => void;
}

const SMALL_BTN: React.CSSProperties = {
  padding: "2px 8px",
  fontSize: "11px",
  border: "1px solid #d1d5db",
  borderRadius: "3px",
  cursor: "pointer",
};

type FilterType = AnnotationType | "all";
type FilterAuthor = "all" | "claude" | "user" | "import";
type FilterStatus = "all" | "pending" | "accepted" | "dismissed";

/** Apply a suggestion annotation's text replacement in the editor */
function applySuggestion(ann: Annotation, editor: TiptapEditor, ydoc: Y.Doc | null): boolean {
  if (ann.type !== "suggestion") return false;

  let newText: string;
  try {
    const parsed = JSON.parse(ann.content);
    newText = parsed.newText;
  } catch {
    console.warn("[SidePanel] Malformed suggestion content for", ann.id);
    return false;
  }

  if (typeof newText !== "string") return false;

  const resolved = annotationToPmRange(ann, editor.state.doc, ydoc);
  if (!resolved) {
    console.warn("[SidePanel] Could not resolve range for suggestion", ann.id);
    return false;
  }

  try {
    editor
      .chain()
      .focus()
      .deleteRange({ from: resolved.from, to: resolved.to })
      .insertContentAt(resolved.from, newText)
      .run();
  } catch (err) {
    console.error("[SidePanel] Editor mutation failed for suggestion", ann.id, err);
    return false;
  }
  return true;
}

export function SidePanel({
  annotations,
  editor,
  ydoc,
  heldCount = 0,
  tandemMode: _tandemMode,
  onModeChange,
  activeDocFormat,
  documentId,
  reviewMode,
  onToggleReviewMode,
  onExitReviewMode,
  activeAnnotationId,
  onActiveAnnotationChange,
}: SidePanelProps) {
  const [filterType, setFilterType] = useState<FilterType>("all");
  const [filterAuthor, setFilterAuthor] = useState<FilterAuthor>("all");
  const [filterStatus, setFilterStatus] = useState<FilterStatus>("all");
  const [reviewIndex, setReviewIndex] = useState(0);
  const reviewIndexRef = useRef(0);
  const [bulkConfirm, setBulkConfirm] = useState<"accept" | "dismiss" | null>(null);
  const bulkConfirmRef = useRef(bulkConfirm);
  bulkConfirmRef.current = bulkConfirm;
  const confirmRef = useRef<HTMLButtonElement>(null);

  // Track recently resolved annotations for timed undo (10s window)
  const [recentlyResolved, setRecentlyResolved] = useState<Set<string>>(new Set());
  // Track the last resolved annotation ID for keyboard undo (Z key)
  const lastResolvedRef = useRef<string | null>(null);
  // Timer IDs for undo window expiry — cancel on undo or unmount
  const undoTimersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());
  useEffect(() => {
    const timers = undoTimersRef.current;
    return () => {
      for (const t of timers.values()) clearTimeout(t);
    };
  }, []);

  // Stable refs for keyboard callbacks to avoid stale closures
  const ydocRef = useRef(ydoc);
  const editorRef = useRef(editor);
  ydocRef.current = ydoc;
  editorRef.current = editor;

  // Single-pass filtering + categorization
  const { filtered, pending, resolved, allPending } = useMemo(() => {
    const filtered: Annotation[] = [];
    const allPending: Annotation[] = [];

    for (const a of annotations) {
      if (a.status === "pending") allPending.push(a);
      const matchType = filterType === "all" || a.type === filterType;
      const matchAuthor = filterAuthor === "all" || a.author === filterAuthor;
      const matchStatus = filterStatus === "all" || a.status === filterStatus;
      if (matchType && matchAuthor && matchStatus) filtered.push(a);
    }

    const pending = filtered.filter((a) => a.status === "pending");
    const resolved = filtered.filter((a) => a.status !== "pending");

    return { filtered, pending, resolved, allPending };
  }, [annotations, filterType, filterAuthor, filterStatus]);

  // Keyboard review targets only pending annotations (unfiltered)
  const reviewTargets = allPending;
  const reviewTargetsRef = useRef(reviewTargets);
  reviewTargetsRef.current = reviewTargets;

  function resolveAnnotation(id: string, status: "accepted" | "dismissed") {
    const y = ydocRef.current;
    if (!y) return;
    const map = y.getMap(Y_MAP_ANNOTATIONS);
    const ann = map.get(id) as Annotation | undefined;
    if (!ann) return;
    map.set(id, { ...ann, status });
    if (status === "accepted" && editorRef.current) {
      const applied = applySuggestion(ann, editorRef.current, ydocRef.current);
      if (!applied) {
        // Revert annotation status — text replacement failed
        map.set(id, { ...ann, status: "pending" });
        return;
      }
    }

    // Track for timed undo
    lastResolvedRef.current = id;
    setRecentlyResolved((prev) => new Set(prev).add(id));
    const existingTimer = undoTimersRef.current.get(id);
    if (existingTimer) clearTimeout(existingTimer);
    const timerId = setTimeout(() => {
      undoTimersRef.current.delete(id);
      setRecentlyResolved((prev) => {
        const next = new Set(prev);
        next.delete(id);
        return next;
      });
      if (lastResolvedRef.current === id) {
        lastResolvedRef.current = null;
      }
    }, 10_000);
    undoTimersRef.current.set(id, timerId);
  }

  /** Revert a resolved annotation back to pending, undoing text changes for accepted suggestions */
  function undoResolveAnnotation(id: string) {
    const y = ydocRef.current;
    if (!y) return;
    const map = y.getMap(Y_MAP_ANNOTATIONS);
    const ann = map.get(id) as Annotation | undefined;
    if (!ann || ann.status === "pending") return;

    // If it was an accepted suggestion, revert the text edit first.
    // If text revert fails, don't revert status — half-undo is worse than no undo.
    if (ann.status === "accepted" && ann.type === "suggestion" && editorRef.current) {
      try {
        const { newText } = JSON.parse(ann.content);
        const oldText = ann.textSnapshot;
        if (typeof newText === "string" && typeof oldText === "string") {
          const resolved = annotationToPmRange(ann, editorRef.current.state.doc, y);
          if (!resolved) {
            console.warn(`[undo] Cannot resolve range for annotation ${id}, skipping`);
            return;
          }
          const currentText = editorRef.current.state.doc.textBetween(resolved.from, resolved.to);
          if (currentText !== newText) {
            console.warn(`[undo] Text changed since accept for annotation ${id}, skipping`);
            return;
          }
          editorRef.current
            .chain()
            .focus()
            .deleteRange({ from: resolved.from, to: resolved.to })
            .insertContentAt(resolved.from, oldText)
            .run();
        }
      } catch (err) {
        console.warn(`[undo] Failed to revert text for annotation ${id}:`, err);
        return;
      }
    }

    // Revert status to pending
    map.set(id, { ...ann, status: "pending" as const });

    // Clean up undo tracking
    const timer = undoTimersRef.current.get(id);
    if (timer) {
      clearTimeout(timer);
      undoTimersRef.current.delete(id);
    }
    setRecentlyResolved((prev) => {
      const next = new Set(prev);
      next.delete(id);
      return next;
    });
    if (lastResolvedRef.current === id) {
      lastResolvedRef.current = null;
    }
  }

  function handleAccept(id: string) {
    resolveAnnotation(id, "accepted");
  }

  function handleDismiss(id: string) {
    resolveAnnotation(id, "dismissed");
  }

  function handleUndo(id: string) {
    undoResolveAnnotation(id);
  }

  function handleEdit(id: string, newContent: string) {
    const y = ydocRef.current;
    if (!y) return;
    const map = y.getMap(Y_MAP_ANNOTATIONS);
    const ann = map.get(id) as Annotation | undefined;
    if (!ann) return;
    map.set(id, { ...ann, content: newContent, editedAt: Date.now() });
  }

  function handleBulkAccept() {
    for (const ann of pending) resolveAnnotation(ann.id, "accepted");
    setBulkConfirm(null);
  }

  function handleBulkDismiss() {
    for (const ann of pending) resolveAnnotation(ann.id, "dismissed");
    setBulkConfirm(null);
  }

  // Scroll editor to an annotation's range
  const scrollToAnnotation = useCallback((ann: Annotation) => {
    const ed = editorRef.current;
    if (!ed) return;
    const resolved = annotationToPmRange(ann, ed.state.doc, ydocRef.current);
    if (!resolved) return;
    ed.chain().focus().setTextSelection({ from: resolved.from, to: resolved.to }).run();
    const domAtPos = ed.view.domAtPos(resolved.from);
    const el = domAtPos.node instanceof HTMLElement ? domAtPos.node : domAtPos.node.parentElement;
    el?.scrollIntoView({ behavior: "smooth", block: "center" });
  }, []);

  // Stable keyboard review callbacks (use refs to avoid dep cascade)
  const navigateReview = useCallback(
    (direction: "next" | "prev") => {
      const targets = reviewTargetsRef.current;
      if (targets.length === 0) return;
      let idx = reviewIndexRef.current;
      idx =
        direction === "next"
          ? (idx + 1) % targets.length
          : (idx - 1 + targets.length) % targets.length;
      reviewIndexRef.current = idx;
      setReviewIndex(idx);
      scrollToAnnotation(targets[idx]);
    },
    [scrollToAnnotation],
  );

  const acceptCurrent = useCallback(() => {
    const targets = reviewTargetsRef.current;
    if (targets.length === 0) return;
    const ann = targets[reviewIndexRef.current];
    if (ann) resolveAnnotation(ann.id, "accepted");
  }, []);

  const dismissCurrent = useCallback(() => {
    const targets = reviewTargetsRef.current;
    if (targets.length === 0) return;
    const ann = targets[reviewIndexRef.current];
    if (ann) resolveAnnotation(ann.id, "dismissed");
  }, []);

  // Reset review index and scroll to first annotation when entering review mode
  const prevReviewModeRef = useRef(false);
  useEffect(() => {
    if (reviewMode && !prevReviewModeRef.current && reviewTargets.length > 0) {
      reviewIndexRef.current = 0;
      setReviewIndex(0);
      scrollToAnnotation(reviewTargets[0]);
    }
    prevReviewModeRef.current = reviewMode;
  }, [reviewMode, reviewTargets, scrollToAnnotation]);

  // Sync activeAnnotationId when review index changes
  useEffect(() => {
    if (reviewMode && reviewTargets.length > 0) {
      onActiveAnnotationChange(reviewTargets[reviewIndex]?.id ?? null);
    } else {
      onActiveAnnotationChange(null);
    }
  }, [reviewMode, reviewIndex, reviewTargets, onActiveAnnotationChange]);

  const scrollToCurrentAndExit = useCallback(() => {
    const targets = reviewTargetsRef.current;
    const ann = targets[reviewIndexRef.current];
    if (ann) scrollToAnnotation(ann);
    onExitReviewMode();
  }, [scrollToAnnotation, onExitReviewMode]);

  const undoLast = useCallback(() => {
    const id = lastResolvedRef.current;
    if (id) undoResolveAnnotation(id);
  }, []);

  const cancelBulkOrExit = useCallback(() => {
    if (bulkConfirmRef.current) {
      setBulkConfirm(null);
    } else {
      onExitReviewMode();
    }
  }, [onExitReviewMode]);

  const reviewCallbacks = useMemo(
    () => ({
      onToggleReviewMode,
      onExitReviewMode,
      navigateReview,
      acceptCurrent,
      dismissCurrent,
      scrollToCurrentAndExit,
      cancelBulkOrExit,
      undoLast,
    }),
    [
      onToggleReviewMode,
      onExitReviewMode,
      navigateReview,
      acceptCurrent,
      dismissCurrent,
      scrollToCurrentAndExit,
      cancelBulkOrExit,
      undoLast,
    ],
  );

  useReviewKeyboard(reviewMode, reviewCallbacks);

  // Focus confirm button when bulk confirmation appears
  useEffect(() => {
    if (bulkConfirm) confirmRef.current?.focus();
  }, [bulkConfirm]);

  // Reset confirmation when filters change (prevents stale Accept/Dismiss All)
  useEffect(() => {
    setBulkConfirm(null);
  }, [filterType, filterAuthor, filterStatus]);

  // Keep review index in bounds when annotations change
  useEffect(() => {
    if (reviewMode && reviewIndexRef.current >= reviewTargets.length) {
      const newIdx = Math.max(0, reviewTargets.length - 1);
      reviewIndexRef.current = newIdx;
      setReviewIndex(newIdx);
    }
  }, [reviewMode, reviewTargets.length]);

  // Auto-exit review mode when no pending left
  useEffect(() => {
    if (reviewMode && reviewTargets.length === 0) {
      onExitReviewMode();
    }
  }, [reviewMode, reviewTargets.length, onExitReviewMode]);

  // Scroll to and flash the annotation card when activeAnnotationId changes externally
  useEffect(() => {
    if (!activeAnnotationId) return;
    // Small delay to let the panel become visible if the tab was just switched
    const timer = setTimeout(() => {
      const card = document.querySelector(`[data-testid="annotation-card-${activeAnnotationId}"]`);
      if (card) {
        card.scrollIntoView({ behavior: "smooth", block: "nearest" });
        card.classList.add("tandem-annotation-flash");
        const onEnd = () => card.classList.remove("tandem-annotation-flash");
        card.addEventListener("animationend", onEnd, { once: true });
      }
    }, 50);
    return () => clearTimeout(timer);
  }, [activeAnnotationId]);

  const listRef = useRef<HTMLDivElement>(null);
  const hasFilters = filterType !== "all" || filterAuthor !== "all" || filterStatus !== "all";
  const activeReviewAnn =
    reviewMode && reviewTargets.length > 0 ? reviewTargets[reviewIndex] : null;

  return (
    <div
      style={{
        width: "100%",
        background: "#fafafa",
        display: "flex",
        flexDirection: "column",
        overflowY: "auto",
      }}
    >
      {/* Held-annotation banner */}
      {heldCount > 0 && (
        <div
          style={{
            padding: "6px 16px",
            background: "#fef3c7",
            borderBottom: "1px solid #fde68a",
            fontSize: "12px",
            color: "#92400e",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <span>
            {heldCount} annotation{heldCount !== 1 ? "s" : ""} held
          </span>
          <button
            onClick={() => onModeChange?.("tandem")}
            style={{
              fontSize: "11px",
              padding: "1px 8px",
              border: "1px solid #fbbf24",
              borderRadius: "4px",
              background: "#fff",
              color: "#92400e",
              cursor: "pointer",
              fontWeight: 500,
            }}
          >
            Show all
          </button>
        </div>
      )}
      {/* Header */}
      <div style={{ padding: "12px 16px", borderBottom: "1px solid #e5e7eb" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <h3 style={{ fontSize: "14px", fontWeight: 600, margin: 0 }}>
            Annotations
            {allPending.length > 0 && (
              <span
                style={{
                  marginLeft: "8px",
                  padding: "1px 6px",
                  fontSize: "11px",
                  background: "#6366f1",
                  color: "white",
                  borderRadius: "10px",
                }}
              >
                {allPending.length}
              </span>
            )}
          </h3>
          <span
            aria-live="polite"
            style={{
              position: "absolute",
              width: 1,
              height: 1,
              overflow: "hidden",
              clip: "rect(0,0,0,0)",
            }}
          >
            {allPending.length} pending annotation{allPending.length !== 1 ? "s" : ""}
          </span>
          {allPending.length > 0 && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end" }}>
              <button
                data-testid="review-mode-btn"
                onClick={onToggleReviewMode}
                title="Keyboard review mode (Ctrl+Shift+R)"
                aria-pressed={reviewMode}
                style={{
                  padding: "2px 8px",
                  fontSize: "11px",
                  border: `1px solid ${reviewMode ? "#6366f1" : "#d1d5db"}`,
                  borderRadius: "3px",
                  background: reviewMode ? "#eef2ff" : "#fff",
                  color: reviewMode ? "#6366f1" : "#6b7280",
                  cursor: "pointer",
                  fontWeight: reviewMode ? 600 : 400,
                }}
              >
                {reviewMode ? "Exit Review" : "Review"}
              </button>
              <div
                data-testid="review-shortcut-hints"
                style={{
                  fontSize: "10px",
                  color: "#9ca3af",
                  marginTop: "2px",
                }}
              >
                Y / N / ↑↓ / Z
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Review mode indicator */}
      {reviewMode && reviewTargets.length > 0 && (
        <div
          style={{
            padding: "8px 16px",
            background: "#eef2ff",
            borderBottom: "1px solid #e5e7eb",
            fontSize: "12px",
            color: "#4338ca",
          }}
        >
          <div aria-live="polite" style={{ fontWeight: 600, marginBottom: "2px" }}>
            Reviewing {reviewIndex + 1} / {reviewTargets.length}
          </div>
          <div style={{ color: "#6366f1" }}>
            Tab: next · Shift+Tab: prev · Y: accept · N: dismiss · Z: undo · E: examine · Esc: exit
          </div>
        </div>
      )}

      {/* Filters */}
      <div
        style={{
          padding: "8px 16px",
          borderBottom: "1px solid #e5e7eb",
          display: "flex",
          gap: "4px",
          flexWrap: "wrap",
          alignItems: "center",
        }}
      >
        <FilterSelect
          testId="filter-type"
          value={filterType}
          onChange={(v) => setFilterType(v as FilterType)}
          options={[
            { value: "all", label: "All types" },
            { value: "highlight", label: "Highlights" },
            { value: "comment", label: "Comments" },
            { value: "suggestion", label: "Suggestions" },
            { value: "question", label: "Questions" },
            { value: "flag", label: "Flags" },
          ]}
        />
        <FilterSelect
          testId="filter-author"
          value={filterAuthor}
          onChange={(v) => setFilterAuthor(v as FilterAuthor)}
          options={[
            { value: "all", label: "Anyone" },
            { value: "claude", label: "Claude" },
            { value: "user", label: "You" },
            { value: "import", label: "Imported" },
          ]}
        />
        <FilterSelect
          testId="filter-status"
          value={filterStatus}
          onChange={(v) => setFilterStatus(v as FilterStatus)}
          options={[
            { value: "all", label: "Any status" },
            { value: "pending", label: "Pending" },
            { value: "accepted", label: "Accepted" },
            { value: "dismissed", label: "Dismissed" },
          ]}
        />
        {hasFilters && (
          <button
            onClick={() => {
              setFilterType("all");
              setFilterAuthor("all");
              setFilterStatus("all");
              listRef.current?.scrollTo({ top: 0 });
            }}
            style={{
              background: "none",
              border: "none",
              color: "#6366f1",
              fontSize: "11px",
              cursor: "pointer",
              padding: "2px 4px",
            }}
          >
            Clear
          </button>
        )}
      </div>

      {/* Apply as tracked changes (docx only) */}
      <div style={{ padding: "4px 16px 0" }}>
        <ApplyChangesButton
          annotations={annotations}
          activeDocFormat={activeDocFormat}
          documentId={documentId}
        />
      </div>

      {/* Bulk actions */}
      {pending.length > 1 && (
        <div
          style={{
            padding: "6px 16px",
            borderBottom: "1px solid #e5e7eb",
            display: "flex",
            gap: "6px",
            alignItems: "center",
          }}
        >
          {bulkConfirm ? (
            (() => {
              const isAccept = bulkConfirm === "accept";
              return (
                <>
                  <span style={{ fontSize: "11px", color: "#374151" }}>
                    {isAccept ? "Acknowledge" : "Dismiss"}{" "}
                    {pending.length === allPending.length
                      ? `${pending.length} annotations?`
                      : `${pending.length} of ${allPending.length} pending?`}
                  </span>
                  <button
                    ref={confirmRef}
                    data-testid="bulk-confirm-btn"
                    onClick={isAccept ? handleBulkAccept : handleBulkDismiss}
                    style={{
                      ...SMALL_BTN,
                      background: isAccept ? "#f0fdf4" : "#fef2f2",
                      color: isAccept ? "#166534" : "#991b1b",
                      fontWeight: 600,
                    }}
                  >
                    Confirm
                  </button>
                  <button
                    data-testid="bulk-cancel-btn"
                    onClick={() => setBulkConfirm(null)}
                    style={{ ...SMALL_BTN, background: "#fff", color: "#6b7280" }}
                  >
                    Cancel
                  </button>
                </>
              );
            })()
          ) : (
            <>
              <button
                data-testid="bulk-accept-btn"
                onClick={() => setBulkConfirm("accept")}
                style={{ ...SMALL_BTN, background: "#f0fdf4", color: "#166534" }}
              >
                Acknowledge All ({pending.length})
              </button>
              <button
                data-testid="bulk-dismiss-btn"
                onClick={() => setBulkConfirm("dismiss")}
                style={{ ...SMALL_BTN, background: "#fef2f2", color: "#991b1b" }}
              >
                Dismiss All
              </button>
            </>
          )}
        </div>
      )}

      {/* Annotation list */}
      <div
        ref={listRef}
        style={{ padding: "8px 16px", flex: 1 }}
        role="list"
        aria-label="Annotations"
      >
        {filtered.length === 0 ? (
          <p role="status" style={{ fontSize: "13px", color: "#9ca3af", marginTop: "8px" }}>
            {hasFilters
              ? "No annotations match filters."
              : "No annotations yet. Open a document to get started."}
          </p>
        ) : (
          <>
            {pending.map((ann) => {
              const isTarget = activeReviewAnn?.id === ann.id;
              return (
                <AnnotationCard
                  key={ann.id}
                  annotation={ann}
                  isReviewTarget={isTarget}
                  onAccept={handleAccept}
                  onDismiss={handleDismiss}
                  onEdit={handleEdit}
                  onClick={() => scrollToAnnotation(ann)}
                />
              );
            })}
            {resolved.length > 0 && (
              <details style={{ marginTop: "12px" }}>
                <summary style={{ fontSize: "12px", color: "#9ca3af", cursor: "pointer" }}>
                  {resolved.length} resolved
                </summary>
                <div role="list" aria-label="Resolved annotations">
                  {resolved.map((ann) => (
                    <AnnotationCard
                      key={ann.id}
                      annotation={ann}
                      onUndo={handleUndo}
                      undoable={recentlyResolved.has(ann.id)}
                      onClick={() => scrollToAnnotation(ann)}
                    />
                  ))}
                </div>
              </details>
            )}
          </>
        )}
      </div>
      <style>{`
        @keyframes tandem-annotation-flash {
          0% { background-color: rgba(99, 102, 241, 0.2); }
          100% { background-color: transparent; }
        }
        .tandem-annotation-flash {
          animation: tandem-annotation-flash 0.8s ease-out;
        }
      `}</style>
    </div>
  );
}
